
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ANIMAL_PRODUCTION : DataObject
	{
		public ANIMAL_PRODUCTION() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"AniID",
            	"AP_Production_Date"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesANIMAL_PRODUCTION
		{  
            public const string AniID = "AniID";
            public const string AP_Production_Date = "AP_Production_Date";
            public const string AP_Birth_Times = "AP_Birth_Times";
            public const string AP_Birth_Alive_Offspring = "AP_Birth_Alive_Offspring";
            public const string AP_Birth_Dead_Offspring = "AP_Birth_Dead_Offspring";
            public const string AP_Birth_Yearling = "AP_Birth_Yearling";
            public const string AP_By_ThrID = "AP_By_ThrID";
		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AniID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PRODUCTION.AniID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PRODUCTION.AniID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public DateTime AP_Production_Date
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesANIMAL_PRODUCTION.AP_Production_Date);
			}
			set
	        {
				base.SetDateTime(ColumnNamesANIMAL_PRODUCTION.AP_Production_Date, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AP_Birth_Times
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Times);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Times, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AP_Birth_Alive_Offspring
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Alive_Offspring);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Alive_Offspring, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AP_Birth_Dead_Offspring
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Dead_Offspring);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Dead_Offspring, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte AP_Birth_Yearling
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Yearling);
			}
			set
	        {
				base.Setsbyte(ColumnNamesANIMAL_PRODUCTION.AP_Birth_Yearling, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AP_By_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PRODUCTION.AP_By_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PRODUCTION.AP_By_ThrID, value);
			}
		}


		#endregion
		
	}
}
