
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ANIMAL_PROPERTY : DataObject
	{
		public ANIMAL_PROPERTY() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
                "AniID",
                "AP_Key",
                "FarmID",
                "UbnID"
            };
		
		}

	
		#region ColumnNames
		public class ColumnNamesANIMAL_PROPERTY
		{  
            public const string UbnID = "UbnID";
            public const string FarmID = "FarmID";
            public const string AniID = "AniID";
            public const string AP_Key = "AP_Key";
            public const string AP_Value = "AP_Value";
		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PROPERTY.UbnID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PROPERTY.UbnID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PROPERTY.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PROPERTY.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AniID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_PROPERTY.AniID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_PROPERTY.AniID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AP_Key
	    {
			get
	        {
				return base.Getstring(ColumnNamesANIMAL_PROPERTY.AP_Key);
			}
			set
	        {
				base.Setstring(ColumnNamesANIMAL_PROPERTY.AP_Key, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AP_Value
	    {
			get
	        {
				return base.Getstring(ColumnNamesANIMAL_PROPERTY.AP_Value);
			}
			set
	        {
				base.Setstring(ColumnNamesANIMAL_PROPERTY.AP_Value, value);
			}
		}

		#endregion
		
	}
}
