
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ANIMALPASSWORD : DataObject
	{
		public ANIMALPASSWORD() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"AP_AniID",
            	"AP_ThrID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesANIMALPASSWORD
		{  
            public const string AP_AniID = "AP_AniID";
            public const string AP_ThrID = "AP_ThrID";
            public const string AP_UserName = "AP_UserName";
            public const string AP_Password = "AP_Password";
            public const string AP_Password_DateTime = "AP_Password_DateTime";
            public const string AP_Password_Days = "AP_Password_Days";
            public const string AP_ProgramID = "AP_ProgramID";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AP_AniID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMALPASSWORD.AP_AniID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMALPASSWORD.AP_AniID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AP_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMALPASSWORD.AP_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMALPASSWORD.AP_ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AP_UserName
	    {
			get
	        {
				return base.Getstring(ColumnNamesANIMALPASSWORD.AP_UserName);
			}
			set
	        {
				base.Setstring(ColumnNamesANIMALPASSWORD.AP_UserName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AP_Password
	    {
			get
	        {
				return base.Getstring(ColumnNamesANIMALPASSWORD.AP_Password);
			}
			set
	        {
				base.Setstring(ColumnNamesANIMALPASSWORD.AP_Password, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime AP_Password_DateTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesANIMALPASSWORD.AP_Password_DateTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesANIMALPASSWORD.AP_Password_DateTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public ushort AP_Password_Days
	    {
			get
	        {
				return base.Getushort(ColumnNamesANIMALPASSWORD.AP_Password_Days);
			}
			set
	        {
				base.Setushort(ColumnNamesANIMALPASSWORD.AP_Password_Days, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AP_ProgramID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMALPASSWORD.AP_ProgramID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMALPASSWORD.AP_ProgramID, value);
			}
		}


		#endregion
		
	}
}
