
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ANIMEDI : DataObject
	{
		public ANIMEDI() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"FarmID",
            	"AniId",
            	"EventId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesANIMEDI
		{  
            public const string FarmID = "FarmID";
            public const string AniId = "AniId";
            public const string EventId = "EventId";
            public const string TreatDate = "TreatDate";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMEDI.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMEDI.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AniId
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMEDI.AniId);
			}
			set
	        {
				base.Setint(ColumnNamesANIMEDI.AniId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int EventId
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMEDI.EventId);
			}
			set
	        {
				base.Setint(ColumnNamesANIMEDI.EventId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime TreatDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesANIMEDI.TreatDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesANIMEDI.TreatDate, value);
			}
		}


		#endregion
		
	}
}
