
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ANIMAL_SHARE_INFO : DataObject
	{
		public ANIMAL_SHARE_INFO() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"AniID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesANIMAL_SHARE_INFO
		{  
            public const string AniID = "AniID";
            public const string Asi_Share_Information = "asi_Share_Information";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AniID
	    {
			get
	        {
				return base.Getint(ColumnNamesANIMAL_SHARE_INFO.AniID);
			}
			set
	        {
				base.Setint(ColumnNamesANIMAL_SHARE_INFO.AniID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long Asi_Share_Information
	    {
			get
	        {
				return base.Getlong(ColumnNamesANIMAL_SHARE_INFO.Asi_Share_Information);
			}
			set
	        {
				base.Setlong(ColumnNamesANIMAL_SHARE_INFO.Asi_Share_Information, value);
			}
		}


		#endregion
		
	}
}
