
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ARTIKEL : DataObject
	{
	    public const int ARTIKEL_HERKOMST_VOER = 1;
        public const int ARTIKEL_HERKOMST_MESTSTOF = 2;
        public const int ARTIKEL_HERKOMST_GEWASBESCHERMING = 3;
        public const int ARTIKEL_HERKOMST_ZAAIGOED = 4;
        public const int ARTIKEL_HERKOMST_POOTGOED = 5;
        public const int ARTIKEL_HERKOMST_MEDICIJNEN = 8;
        public const int ARTIKEL_HERKOMST_DIVERSE = 99;

		public ARTIKEL() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"ArtId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesARTIKEL
		{  
            public const string ArtId = "ArtId";
            public const string AdmisNumber = "AdmisNumber";
            public const string ArtNumber = "ArtNumber";
            public const string ArtNaam = "ArtNaam";
            public const string ArtGrootboekInk = "ArtGrootboekInk";
            public const string ArtGrootboekVerk = "ArtGrootboekVerk";
            public const string ArtDoorboeken = "ArtDoorboeken";
            public const string ArtVasteprijs = "ArtVasteprijs";
            public const string ArtInkoopPrijs = "ArtInkoopPrijs";
            public const string ArtBTWcode = "ArtBTWcode";
            public const string ArtAantalPer = "ArtAantalPer";
            public const string ArtPrijsPer = "ArtPrijsPer";
            public const string ArtPrijsExclusief = "ArtPrijsExclusief";
            public const string ArtAfdrukdecimalen = "ArtAfdrukdecimalen";
            public const string ArtNormRE = "ArtNormRE";
            public const string ArtNormP = "ArtNormP";
            public const string ArtNormK = "ArtNormK";
            public const string ArtDrogestof = "ArtDrogestof";
            public const string ArtValutacode = "ArtValutacode";
            public const string ArtWeekNotering = "ArtWeekNotering";
            public const string ArtLayoutnummer = "ArtLayoutnummer";
            public const string ArtBevleesdheid = "ArtBevleesdheid";
            public const string ArtTypeToeslag = "ArtTypeToeslag";
            public const string ArtMinasCategorie = "ArtMinasCategorie";
            public const string ArtMinasSubCategorie = "ArtMinasSubCategorie";
            public const string ArtGewichtsfactor = "ArtGewichtsfactor";
            public const string ArtGroep = "ArtGroep";
            public const string ArtDiermineraalgroep = "ArtDiermineraalgroep";
            public const string ArtDagboekInkoop = "ArtDagboekInkoop";
            public const string ArtDagboekVerkoop = "ArtDagboekVerkoop";
            public const string ArtEenheid = "ArtEenheid";
            public const string ArtToeslagTabel = "ArtToeslagTabel";
            public const string ArtAfleverplanning = "ArtAfleverplanning";
            public const string ArtExtravelden = "ArtExtravelden";
            public const string ArtHerkomst = "ArtHerkomst";
            public const string ArtMinimaleVrd = "ArtMinimaleVrd";
            public const string ArtBestelgrootte = "ArtBestelgrootte";
            public const string ArtUser = "ArtUser";
            public const string ArtUserSec = "ArtUserSec";
            public const string ArtUserThird = "ArtUserThird";
            public const string ArtActieId = "ArtActieId";
            public const string ArtThrId = "ArtThrId";
            public const string UbnID = "UbnID";
            public const string ArtContactId = "ArtContactId";
            public const string ArtMemo = "ArtMemo";
            public const string ArtInternetUpdate = "ArtInternetUpdate";
            public const string ArtShowOnWebsite = "ArtShowOnWebsite";
            public const string ArtIncasso = "ArtIncasso";
            public const string ArtStandaardEenheid = "ArtStandaardEenheid";
            public const string ArtStandaardHoeveelheid = "ArtStandaardHoeveelheid";
            public const string ArtKorting = "ArtKorting";
            public const string ArtBarcode = "ArtBarcode";
            public const string ArtKGNP = "ArtKGNP";
            public const string ArtLayoutid = "ArtLayoutid";
            public const string ArtDagenHoudbaar = "ArtDagenHoudbaar";
            public const string ArtHoudbaarWaarsch = "ArtHoudbaarWaarsch";
            public const string ArtStdMaakHvlhd = "ArtStdMaakHvlhd";
            public const string ArtStdProduct = "ArtStdProduct";
            public const string ArtHeeftVoorraad = "ArtHeeftVoorraad";
            public const string ArtSvId = "ArtSvId";
            public const string Art_Print_Re_N = "Art_Print_Re_N";
            public const string Art_Print_P_P2O5 = "Art_Print_P_P2O5";
            public const string Art_Print_DS = "Art_Print_DS";
            public const string Art_Print_Per_Vracht = "Art_Print_Per_Vracht";
            public const string Art_In_Handel = "Art_In_Handel";
            public const string Art_Uit_Handel = "Art_Uit_Handel";
            public const string Art_Wachten_Op_Aantal = "Art_Wachten_Op_Aantal";
            public const string Art_Max_Afwijking_Aantal = "Art_Max_Afwijking_Aantal";
            public const string Art_Std_Verpakking_ArtId = "Art_Std_Verpakking_ArtId";
            public const string Art_Inc_Verpakkingsprijs = "Art_Inc_Verpakkingsprijs";
            public const string Art_Std_Inkoop_Prijs = "Art_Std_Inkoop_Prijs";
            public const string Art_IsRL = "Art_IsRL";
            public const string Art_IsGeklast = "Art_IsGeklast";
            public const string Art_IsMannelijk = "Art_IsMannelijk";
            public const string Art_Fabrikant = "Art_Fabrikant";
            public const string Art_Std_Gewicht = "Art_Std_Gewicht";
            public const string ArtTijdAantalPer = "ArtTijdAantalPer";
            public const string ArtTijdStandaardeenheid = "ArtTijdStandaardeenheid";
            public const string ArtTijdVasteTijd = "ArtTijdVasteTijd";
            public const string Art_Analyse_Prijs = "Art_Analyse_Prijs";
            public const string Art_productielokatie = "Art_productielokatie";
            public const string Art_man_uren = "Art_man_uren";
            public const string Artvoorraaddatum = "Artvoorraaddatum";
            public const string Artvoorraadbeginaantal = "Artvoorraadbeginaantal";
            public const string ArtBasisVoorraad = "ArtBasisVoorraad";
            public const string Art_Aantal_Per_Pallet = "Art_Aantal_Per_Pallet";
            public const string ArtKortingLeverancier = "artKortingLeverancier";
            public const string Art_Deel_Factuur_Artikel = "Art_Deel_Factuur_Artikel";
            public const string Art_Kassa = "Art_Kassa";
            public const string Art_Handheld = "Art_Handheld";
            public const string ArtNormVEM = "ArtNormVEM";
            public const string Art_Adres = "Art_Adres";
            public const string Art_Postcode = "Art_Postcode";
            public const string Art_Plaats = "Art_Plaats";
            public const string Art_EAN = "Art_EAN";
            public const string ArtNormVevi = "ArtNormVevi";
            public const string BullAiNumber = "BullAiNumber";
            public const string Bex_ArtID = "Bex_ArtID";
            public const string IDO_hierarchie = "IDO_hierarchie";
            public const string Art_Prijs_Gesexed = "Art_Prijs_Gesexed";
            public const string Art_Prijs_Gesexed_Inkoop = "Art_Prijs_Gesexed_Inkoop";
            public const string ArtAbbreviation = "ArtAbbreviation";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int ArtId
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtId);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long AdmisNumber
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.AdmisNumber);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.AdmisNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtNaam
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtNaam);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtNaam, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtGrootboekInk
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtGrootboekInk);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtGrootboekInk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtGrootboekVerk
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtGrootboekVerk);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtGrootboekVerk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtDoorboeken
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtDoorboeken);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtDoorboeken, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtVasteprijs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtVasteprijs);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtVasteprijs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtInkoopPrijs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtInkoopPrijs);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtInkoopPrijs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtBTWcode
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtBTWcode);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtBTWcode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtAantalPer
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtAantalPer);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtAantalPer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtPrijsPer
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtPrijsPer);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtPrijsPer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtPrijsExclusief
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtPrijsExclusief);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtPrijsExclusief, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtAfdrukdecimalen
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtAfdrukdecimalen);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtAfdrukdecimalen, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtNormRE
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtNormRE);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtNormRE, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtNormP
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtNormP);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtNormP, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtNormK
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtNormK);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtNormK, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtDrogestof
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtDrogestof);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtDrogestof, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtValutacode
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtValutacode);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtValutacode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtWeekNotering
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtWeekNotering);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtWeekNotering, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtLayoutnummer
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtLayoutnummer);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtLayoutnummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtBevleesdheid
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtBevleesdheid);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtBevleesdheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtTypeToeslag
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtTypeToeslag);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtTypeToeslag, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtMinasCategorie
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtMinasCategorie);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtMinasCategorie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtMinasSubCategorie
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtMinasSubCategorie);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtMinasSubCategorie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtGewichtsfactor
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtGewichtsfactor);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtGewichtsfactor, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtGroep
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtGroep);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtGroep, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtDiermineraalgroep
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtDiermineraalgroep);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtDiermineraalgroep, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtDagboekInkoop
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtDagboekInkoop);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtDagboekInkoop, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtDagboekVerkoop
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtDagboekVerkoop);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtDagboekVerkoop, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtEenheid
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtEenheid);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtToeslagTabel
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtToeslagTabel);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtToeslagTabel, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtAfleverplanning
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtAfleverplanning);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtAfleverplanning, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtExtravelden
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtExtravelden);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtExtravelden, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtHerkomst
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtHerkomst);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtHerkomst, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtMinimaleVrd
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtMinimaleVrd);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtMinimaleVrd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtBestelgrootte
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtBestelgrootte);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtBestelgrootte, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtUser
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtUser);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtUser, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtUserSec
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtUserSec);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtUserSec, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtUserThird
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtUserThird);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtUserThird, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtActieId
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtActieId);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtActieId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtThrId
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtThrId);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnID
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.UbnID);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.UbnID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtContactId
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtContactId);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtContactId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtMemo
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtMemo);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtMemo, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtInternetUpdate
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtInternetUpdate);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtInternetUpdate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtShowOnWebsite
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtShowOnWebsite);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtShowOnWebsite, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte ArtIncasso
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.ArtIncasso);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.ArtIncasso, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtStandaardEenheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtStandaardEenheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtStandaardEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtStandaardHoeveelheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtStandaardHoeveelheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtStandaardHoeveelheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtKorting
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtKorting);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtKorting, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtBarcode
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtBarcode);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtBarcode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtKGNP
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtKGNP);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtKGNP, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtLayoutid
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtLayoutid);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtLayoutid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtDagenHoudbaar
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtDagenHoudbaar);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtDagenHoudbaar, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public long ArtHoudbaarWaarsch
	    {
			get
	        {
				return base.Getlong(ColumnNamesARTIKEL.ArtHoudbaarWaarsch);
			}
			set
	        {
				base.Setlong(ColumnNamesARTIKEL.ArtHoudbaarWaarsch, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtStdMaakHvlhd
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtStdMaakHvlhd);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtStdMaakHvlhd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtStdProduct
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtStdProduct);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtStdProduct, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public byte ArtHeeftVoorraad
	    {
			get
	        {
				return base.Getbyte(ColumnNamesARTIKEL.ArtHeeftVoorraad);
			}
			set
	        {
				base.Setbyte(ColumnNamesARTIKEL.ArtHeeftVoorraad, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ArtSvId
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.ArtSvId);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.ArtSvId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Print_Re_N
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Print_Re_N);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Print_Re_N, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Print_P_P2O5
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Print_P_P2O5);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Print_P_P2O5, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Print_DS
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Print_DS);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Print_DS, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Print_Per_Vracht
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Print_Per_Vracht);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Print_Per_Vracht, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Art_In_Handel
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesARTIKEL.Art_In_Handel);
			}
			set
	        {
				base.SetDateTime(ColumnNamesARTIKEL.Art_In_Handel, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Art_Uit_Handel
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesARTIKEL.Art_Uit_Handel);
			}
			set
	        {
				base.SetDateTime(ColumnNamesARTIKEL.Art_Uit_Handel, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Wachten_Op_Aantal
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Wachten_Op_Aantal);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Wachten_Op_Aantal, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Max_Afwijking_Aantal
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Max_Afwijking_Aantal);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Max_Afwijking_Aantal, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Art_Std_Verpakking_ArtId
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Art_Std_Verpakking_ArtId);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Art_Std_Verpakking_ArtId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Inc_Verpakkingsprijs
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Inc_Verpakkingsprijs);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Inc_Verpakkingsprijs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Std_Inkoop_Prijs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Std_Inkoop_Prijs);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Std_Inkoop_Prijs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_IsRL
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_IsRL);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_IsRL, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_IsGeklast
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_IsGeklast);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_IsGeklast, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_IsMannelijk
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_IsMannelijk);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_IsMannelijk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Art_Fabrikant
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Art_Fabrikant);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Art_Fabrikant, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Std_Gewicht
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Std_Gewicht);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Std_Gewicht, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtTijdAantalPer
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtTijdAantalPer);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtTijdAantalPer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtTijdStandaardeenheid
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtTijdStandaardeenheid);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtTijdStandaardeenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ArtTijdVasteTijd
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.ArtTijdVasteTijd);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.ArtTijdVasteTijd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Analyse_Prijs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Analyse_Prijs);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Analyse_Prijs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Art_productielokatie
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Art_productielokatie);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Art_productielokatie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Art_man_uren
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Art_man_uren);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Art_man_uren, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Artvoorraaddatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesARTIKEL.Artvoorraaddatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesARTIKEL.Artvoorraaddatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Artvoorraadbeginaantal
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Artvoorraadbeginaantal);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Artvoorraadbeginaantal, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtBasisVoorraad
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtBasisVoorraad);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtBasisVoorraad, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Aantal_Per_Pallet
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Aantal_Per_Pallet);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Aantal_Per_Pallet, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtKortingLeverancier
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtKortingLeverancier);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtKortingLeverancier, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Art_Deel_Factuur_Artikel
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Art_Deel_Factuur_Artikel);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Art_Deel_Factuur_Artikel, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Kassa
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Kassa);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Kassa, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Art_Handheld
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesARTIKEL.Art_Handheld);
			}
			set
	        {
				base.Setsbyte(ColumnNamesARTIKEL.Art_Handheld, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtNormVEM
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtNormVEM);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtNormVEM, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Art_Adres
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.Art_Adres);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.Art_Adres, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Art_Postcode
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.Art_Postcode);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.Art_Postcode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Art_Plaats
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.Art_Plaats);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.Art_Plaats, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Art_EAN
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.Art_EAN);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.Art_EAN, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ArtNormVevi
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.ArtNormVevi);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.ArtNormVevi, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string BullAiNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.BullAiNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.BullAiNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Bex_ArtID
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL.Bex_ArtID);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL.Bex_ArtID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string IDO_hierarchie
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL.IDO_hierarchie);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL.IDO_hierarchie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Prijs_Gesexed
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Prijs_Gesexed);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Prijs_Gesexed, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Art_Prijs_Gesexed_Inkoop
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL.Art_Prijs_Gesexed_Inkoop);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL.Art_Prijs_Gesexed_Inkoop, value);
			}
		}

        [System.ComponentModel.DataObjectField(false, false, false)]
        public string ArtAbbreviation
        {
            get
            {
                return base.Getstring(ColumnNamesARTIKEL.ArtAbbreviation);
            }
            set
            {
                base.Setstring(ColumnNamesARTIKEL.ArtAbbreviation, value);
            }
        }

        #endregion

    }
}
