
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ARTIKEL_MEDIC_WERKZAMESTOF : DataObject
	{
		public ARTIKEL_MEDIC_WERKZAMESTOF() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"amwsId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF
		{  
            public const string AmwsId = "amwsId";
            public const string AmwsNaam = "amwsNaam";
            public const string AmwsEenheid = "amwsEenheid";
            public const string AmwsHoeveelheid = "amwsHoeveelheid";
            public const string AmwsCorrectieFactorDosering = "amwsCorrectieFactorDosering";
            public const string AmwsDoseringsVorm = "amwsDoseringsVorm";
            public const string AmwsFidinId = "amwsFidinId";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int amwsId
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsId);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string amwsNaam
	    {
			get
	        {
				return base.Getstring(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsNaam);
			}
			set
	        {
				base.Setstring(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsNaam, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int amwsEenheid
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsEenheid);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double amwsHoeveelheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsHoeveelheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsHoeveelheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double amwsCorrectieFactorDosering
	    {
			get
	        {
				return base.Getdouble(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsCorrectieFactorDosering);
			}
			set
	        {
				base.Setdouble(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsCorrectieFactorDosering, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int amwsDoseringsVorm
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsDoseringsVorm);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsDoseringsVorm, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int amwsFidinId
	    {
			get
	        {
				return base.Getint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsFidinId);
			}
			set
	        {
				base.Setint(ColumnNamesARTIKEL_MEDIC_WERKZAMESTOF.AmwsFidinId, value);
			}
		}


		#endregion
		
	}
}
