
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class BCURVDAY : DataObject
	{
		public BCURVDAY() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr",
            	"Weeknr",
            	"Dagnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesBCURVDAY
		{  
            public const string Internalnr = "Internalnr";
            public const string Weeknr = "Weeknr";
            public const string Dagnr = "Dagnr";
            public const string Kgvoer1 = "Kgvoer1";
            public const string Kgvoer2 = "Kgvoer2";
            public const string Kgvoer3 = "Kgvoer3";
            public const string Kgvoer4 = "Kgvoer4";
            public const string Kgvoer5 = "Kgvoer5";
            public const string Kgvoer6 = "Kgvoer6";
            public const string Kgvoer7 = "Kgvoer7";
            public const string Kgvoer8 = "Kgvoer8";
            public const string Kgvoer9 = "Kgvoer9";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesBCURVDAY.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesBCURVDAY.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Weeknr
	    {
			get
	        {
				return base.Getint(ColumnNamesBCURVDAY.Weeknr);
			}
			set
	        {
				base.Setint(ColumnNamesBCURVDAY.Weeknr, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Dagnr
	    {
			get
	        {
				return base.Getint(ColumnNamesBCURVDAY.Dagnr);
			}
			set
	        {
				base.Setint(ColumnNamesBCURVDAY.Dagnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer1
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer1);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer1, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer2
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer2);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer2, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer3
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer3);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer3, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer4
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer4);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer4, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer5
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer5);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer5, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer6
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer6);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer6, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer7
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer7);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer7, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer8
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer8);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer8, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Kgvoer9
	    {
			get
	        {
				return base.Getfloat(ColumnNamesBCURVDAY.Kgvoer9);
			}
			set
	        {
				base.Setfloat(ColumnNamesBCURVDAY.Kgvoer9, value);
			}
		}


		#endregion
		
	}
}
