/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
    public class BUYING : DataObject
    {
        public BUYING() : base(Database.animal)
        {
            UpdateParams = new String[]
            {
                "MovId"
            };

        }


        #region ColumnNames
        public class ColumnNamesBUYING
        {
            public const string MovId = "MovId";
            public const string PurRegisteryNumber = "PurRegisteryNumber";
            public const string PurPrice = "PurPrice";
            public const string PurVAT = "PurVAT";
            public const string PurShowIncludingVAT = "PurShowIncludingVAT";
            public const string PurBTWPerc = "PurBTWPerc";
            public const string PurPriceEuro = "PurPriceEuro";
            public const string PurCurrencyEuro = "PurCurrencyEuro";
            public const string PurWeight = "PurWeight";
            public const string PurClassificationMeat = "PurClassificationMeat";
            public const string PurDeviationMeat = "PurDeviationMeat";
            public const string Mestnummer = "Mestnummer";
            public const string Stablenumber = "Stablenumber";
            public const string PurOrigin = "PurOrigin";
            public const string PurClassificationFat = "PurClassificationFat";
            public const string PurDeviationFat = "PurDeviationFat";
            public const string PurKind = "PurKind";
            public const string PurWithSale = "PurWithSale";
            public const string PurTransporter = "PurTransporter";
            public const string PurHandelaar = "PurHandelaar";
            public const string PurDirectDelivery = "PurDirectDelivery";
            public const string PurSubsidy = "PurSubsidy";
            public const string PurTransportID = "PurTransportID";
            public const string PurLicensePlate = "PurLicensePlate";
            public const string PurAniState = "PurAniState";
            public const string PurVersienrPaspoort = "PurVersienrPaspoort";
            public const string PurNrGezondheidsCert = "PurNrGezondheidsCert";
            public const string PurOrigin_UBNid = "PurOrigin_UBNid";

        }
        #endregion

        #region Properties

        [System.ComponentModel.DataObjectField(true, false, false)]
        public int MovId
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.MovId);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.MovId, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public string PurRegisteryNumber
        {
            get
            {
                return base.Getstring(ColumnNamesBUYING.PurRegisteryNumber);
            }
            set
            {
                base.Setstring(ColumnNamesBUYING.PurRegisteryNumber, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public double PurPrice
        {
            get
            {
                return base.Getdouble(ColumnNamesBUYING.PurPrice);
            }
            set
            {
                base.Setdouble(ColumnNamesBUYING.PurPrice, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public double PurVAT
        {
            get
            {
                return base.Getdouble(ColumnNamesBUYING.PurVAT);
            }
            set
            {
                base.Setdouble(ColumnNamesBUYING.PurVAT, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public sbyte PurShowIncludingVAT
        {
            get
            {
                return base.Getsbyte(ColumnNamesBUYING.PurShowIncludingVAT);
            }
            set
            {
                base.Setsbyte(ColumnNamesBUYING.PurShowIncludingVAT, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurBTWPerc
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurBTWPerc);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurBTWPerc, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public double PurPriceEuro
        {
            get
            {
                return base.Getdouble(ColumnNamesBUYING.PurPriceEuro);
            }
            set
            {
                base.Setdouble(ColumnNamesBUYING.PurPriceEuro, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public sbyte PurCurrencyEuro
        {
            get
            {
                return base.Getsbyte(ColumnNamesBUYING.PurCurrencyEuro);
            }
            set
            {
                base.Setsbyte(ColumnNamesBUYING.PurCurrencyEuro, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public double PurWeight
        {
            get
            {
                return base.Getdouble(ColumnNamesBUYING.PurWeight);
            }
            set
            {
                base.Setdouble(ColumnNamesBUYING.PurWeight, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurClassificationMeat
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurClassificationMeat);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurClassificationMeat, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurDeviationMeat
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurDeviationMeat);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurDeviationMeat, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public string Mestnummer
        {
            get
            {
                return base.Getstring(ColumnNamesBUYING.Mestnummer);
            }
            set
            {
                base.Setstring(ColumnNamesBUYING.Mestnummer, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int Stablenumber
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.Stablenumber);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.Stablenumber, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurOrigin
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurOrigin);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurOrigin, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurClassificationFat
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurClassificationFat);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurClassificationFat, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurDeviationFat
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurDeviationFat);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurDeviationFat, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurKind
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurKind);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurKind, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurWithSale
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurWithSale);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurWithSale, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurTransporter
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurTransporter);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurTransporter, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurHandelaar
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurHandelaar);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurHandelaar, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurDirectDelivery
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurDirectDelivery);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurDirectDelivery, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurSubsidy
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurSubsidy);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurSubsidy, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurTransportID
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurTransportID);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurTransportID, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public string PurLicensePlate
        {
            get
            {
                return base.Getstring(ColumnNamesBUYING.PurLicensePlate);
            }
            set
            {
                base.Setstring(ColumnNamesBUYING.PurLicensePlate, value);
            }
        }
        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurAniState
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurAniState);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurAniState, value);
            }
        }
		
        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurVersienrPaspoort
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurVersienrPaspoort);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurVersienrPaspoort, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public string PurNrGezondheidsCert
        {
            get
            {
                return base.Getstring(ColumnNamesBUYING.PurNrGezondheidsCert);
            }
            set
            {
                base.Setstring(ColumnNamesBUYING.PurNrGezondheidsCert, value);
            }
        }

        [System.ComponentModel.DataObjectField(false, false, false)]
        public int PurOrigin_UBNid
        {
            get
            {
                return base.Getint(ColumnNamesBUYING.PurOrigin_UBNid);
            }
            set
            {
                base.Setint(ColumnNamesBUYING.PurOrigin_UBNid, value);
            }
        }

        #endregion

    }
}
