
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class CCURVDAY : DataObject
	{
		public CCURVDAY() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr",
            	"Weeknr",
            	"Dagnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesCCURVDAY
		{  
            public const string Internalnr = "Internalnr";
            public const string Weeknr = "Weeknr";
            public const string Dagnr = "Dagnr";
            public const string Gramvoer1 = "Gramvoer1";
            public const string Gramvoer2 = "Gramvoer2";
            public const string Gramvoer3 = "Gramvoer3";
            public const string Gramvoer4 = "Gramvoer4";
            public const string Gramvoer5 = "Gramvoer5";
            public const string Gramvoer6 = "Gramvoer6";
            public const string Gramvoer7 = "Gramvoer7";
            public const string Gramvoer8 = "Gramvoer8";
            public const string Gramvoer9 = "Gramvoer9";
            public const string Liters = "Liters";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Weeknr
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Weeknr);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Weeknr, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Dagnr
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Dagnr);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Dagnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer1
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer1);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer1, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer2
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer2);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer2, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer3
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer3);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer3, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer4
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer4);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer4, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer5
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer5);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer5, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer6
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer6);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer6, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer7
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer7);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer7, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer8
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer8);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer8, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Gramvoer9
	    {
			get
	        {
				return base.Getint(ColumnNamesCCURVDAY.Gramvoer9);
			}
			set
	        {
				base.Setint(ColumnNamesCCURVDAY.Gramvoer9, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Liters
	    {
			get
	        {
				return base.Getfloat(ColumnNamesCCURVDAY.Liters);
			}
			set
	        {
				base.Setfloat(ColumnNamesCCURVDAY.Liters, value);
			}
		}


		#endregion
		
	}
}
