
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class CHIP_BOX : DataObject
	{
		public CHIP_BOX() : base(Database.chip_supplier)
		{
			UpdateParams = new String[] 
			{
            	"Cb_Box_ID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesCHIP_BOX
		{  
            public const string Cb_Box_ID = "cb_Box_ID";
            public const string Cb_Barcode = "cb_Barcode";
            public const string Cb_Upload_Date = "cb_Upload_Date";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int cb_Box_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesCHIP_BOX.Cb_Box_ID);
			}
			set
	        {
				base.Setint(ColumnNamesCHIP_BOX.Cb_Box_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string cb_Barcode
	    {
			get
	        {
				return base.Getstring(ColumnNamesCHIP_BOX.Cb_Barcode);
			}
			set
	        {
				base.Setstring(ColumnNamesCHIP_BOX.Cb_Barcode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime cb_Upload_Date
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesCHIP_BOX.Cb_Upload_Date);
			}
			set
	        {
				base.SetDateTime(ColumnNamesCHIP_BOX.Cb_Upload_Date, value);
			}
		}


		#endregion
		
	}
}
