
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class COMPLAINTS : DataObject
	{
		public COMPLAINTS() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"CM_ID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesCOMPLAINTS
		{  
            public const string CM_ID = "CM_ID";
            public const string FarmID = "FarmID";
            public const string UBNID = "UBNID";
            public const string ThrID = "ThrID";
            public const string CM_ReceptionDate = "CM_ReceptionDate";
            public const string CM_Treated_Date = "CM_Treated_Date";
            public const string CM_Anonymous = "CM_Anonymous";
            public const string CM_Reply_to_Email = "CM_Reply_to_Email";
            public const string CM_Employee = "CM_Employee";
            public const string CM_Description = "CM_Description";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int CM_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesCOMPLAINTS.CM_ID);
			}
			set
	        {
				base.Setint(ColumnNamesCOMPLAINTS.CM_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesCOMPLAINTS.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesCOMPLAINTS.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UBNID
	    {
			get
	        {
				return base.Getint(ColumnNamesCOMPLAINTS.UBNID);
			}
			set
	        {
				base.Setint(ColumnNamesCOMPLAINTS.UBNID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesCOMPLAINTS.ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesCOMPLAINTS.ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime CM_ReceptionDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesCOMPLAINTS.CM_ReceptionDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesCOMPLAINTS.CM_ReceptionDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime CM_Treated_Date
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesCOMPLAINTS.CM_Treated_Date);
			}
			set
	        {
				base.SetDateTime(ColumnNamesCOMPLAINTS.CM_Treated_Date, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte CM_Anonymous
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesCOMPLAINTS.CM_Anonymous);
			}
			set
	        {
				base.Setsbyte(ColumnNamesCOMPLAINTS.CM_Anonymous, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string CM_Reply_to_Email
	    {
			get
	        {
				return base.Getstring(ColumnNamesCOMPLAINTS.CM_Reply_to_Email);
			}
			set
	        {
				base.Setstring(ColumnNamesCOMPLAINTS.CM_Reply_to_Email, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string CM_Employee
	    {
			get
	        {
				return base.Getstring(ColumnNamesCOMPLAINTS.CM_Employee);
			}
			set
	        {
				base.Setstring(ColumnNamesCOMPLAINTS.CM_Employee, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string CM_Description
	    {
			get
	        {
				return base.Getstring(ColumnNamesCOMPLAINTS.CM_Description);
			}
			set
	        {
				base.Setstring(ColumnNamesCOMPLAINTS.CM_Description, value);
			}
		}


		#endregion
		
	}
}
