
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class DHZ : DataObject
	{
		public DHZ() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesDHZ
		{  
            public const string Internalnr = "Internalnr";
            public const string UbnId = "UbnId";
            public const string FarmNumber = "FarmNumber";
            public const string AniId = "AniId";
            public const string AniLifenumber = "AniLifenumber";
            public const string AniWorknumber = "AniWorknumber";
            public const string AniName = "AniName";
            public const string InsDate = "InsDate";
            public const string EndDate = "EndDate";
            public const string ReportDate = "ReportDate";
            public const string ReportTime = "ReportTime";
            public const string Report = "Report";
            public const string BullLifeNumber = "BullLifeNumber";
            public const string BullName = "BullName";
            public const string BullAInumber = "BullAInumber";
            public const string ChargeNumber = "ChargeNumber";
            public const string InsInfo = "InsInfo";
            public const string InsNumber = "InsNumber";
            public const string Frozen = "Frozen";
            public const string ReportTo = "ReportTo";
            public const string Inseminator = "Inseminator";
            public const string Imported = "Imported";
            public const string InsAmount = "InsAmount";
            public const string EventID = "EventID";
            public const string T4CInsemId = "T4CInsemId";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FarmNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.FarmNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.FarmNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AniId
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.AniId);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.AniId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AniLifenumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.AniLifenumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.AniLifenumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AniWorknumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.AniWorknumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.AniWorknumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string AniName
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.AniName);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.AniName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime InsDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesDHZ.InsDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesDHZ.InsDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime EndDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesDHZ.EndDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesDHZ.EndDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ReportDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesDHZ.ReportDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesDHZ.ReportDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ReportTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesDHZ.ReportTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesDHZ.ReportTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Report
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesDHZ.Report);
			}
			set
	        {
				base.Setsbyte(ColumnNamesDHZ.Report, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string BullLifeNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.BullLifeNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.BullLifeNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string BullName
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.BullName);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.BullName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string BullAInumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.BullAInumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.BullAInumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ChargeNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.ChargeNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.ChargeNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string InsInfo
	    {
			get
	        {
				return base.Getstring(ColumnNamesDHZ.InsInfo);
			}
			set
	        {
				base.Setstring(ColumnNamesDHZ.InsInfo, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int InsNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.InsNumber);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.InsNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte Frozen
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesDHZ.Frozen);
			}
			set
	        {
				base.Setsbyte(ColumnNamesDHZ.Frozen, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ReportTo
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.ReportTo);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.ReportTo, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Inseminator
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.Inseminator);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.Inseminator, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Imported
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.Imported);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.Imported, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int InsAmount
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.InsAmount);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.InsAmount, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int EventID
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.EventID);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.EventID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int T4CInsemId
	    {
			get
	        {
				return base.Getint(ColumnNamesDHZ.T4CInsemId);
			}
			set
	        {
				base.Setint(ColumnNamesDHZ.T4CInsemId, value);
			}
		}


		#endregion
		
	}
}
