
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class DRZAAI : DataObject
	{
		public DRZAAI() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"DrzPerceelid",
            	"DrzActid"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesDRZAAI
		{  
            public const string DrzPerceelid = "DrzPerceelid";
            public const string DrzActid = "DrzActid";
            public const string DrzGewas = "DrzGewas";
            public const string DrzRas = "DrzRas";
            public const string DrzHoeveelheid = "DrzHoeveelheid";
            public const string DrzEenheid = "DrzEenheid";
            public const string DrzOpkomstdatum = "DrzOpkomstdatum";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int DrzPerceelid
	    {
			get
	        {
				return base.Getint(ColumnNamesDRZAAI.DrzPerceelid);
			}
			set
	        {
				base.Setint(ColumnNamesDRZAAI.DrzPerceelid, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int DrzActid
	    {
			get
	        {
				return base.Getint(ColumnNamesDRZAAI.DrzActid);
			}
			set
	        {
				base.Setint(ColumnNamesDRZAAI.DrzActid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int DrzGewas
	    {
			get
	        {
				return base.Getint(ColumnNamesDRZAAI.DrzGewas);
			}
			set
	        {
				base.Setint(ColumnNamesDRZAAI.DrzGewas, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string DrzRas
	    {
			get
	        {
				return base.Getstring(ColumnNamesDRZAAI.DrzRas);
			}
			set
	        {
				base.Setstring(ColumnNamesDRZAAI.DrzRas, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double DrzHoeveelheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesDRZAAI.DrzHoeveelheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesDRZAAI.DrzHoeveelheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int DrzEenheid
	    {
			get
	        {
				return base.Getint(ColumnNamesDRZAAI.DrzEenheid);
			}
			set
	        {
				base.Setint(ColumnNamesDRZAAI.DrzEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime DrzOpkomstdatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesDRZAAI.DrzOpkomstdatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesDRZAAI.DrzOpkomstdatum, value);
			}
		}


		#endregion
		
	}
}
