
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FABRPOST : DataObject
	{
		public FABRPOST() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"CooperationNumber",
            	"Position"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFABRPOST
		{  
            public const string CooperationNumber = "CooperationNumber";
            public const string Position = "Position";
            public const string BookNumber = "BookNumber";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int CooperationNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesFABRPOST.CooperationNumber);
			}
			set
	        {
				base.Setint(ColumnNamesFABRPOST.CooperationNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Position
	    {
			get
	        {
				return base.Getint(ColumnNamesFABRPOST.Position);
			}
			set
	        {
				base.Setint(ColumnNamesFABRPOST.Position, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string BookNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesFABRPOST.BookNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesFABRPOST.BookNumber, value);
			}
		}


		#endregion
		
	}
}
