
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FACTUUR : DataObject
	{
		public FACTUUR() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"FactId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFACTUUR
		{  
            public const string FactId = "FactId";
            public const string FarmId = "FarmId";
            public const string UbnID = "UbnID";
            public const string FactDagBoekId = "FactDagBoekId";
            public const string FactRelatieId = "FactRelatieId";
            public const string FactSoort = "FactSoort";
            public const string FactNummer = "FactNummer";
            public const string FactDatum = "FactDatum";
            public const string FactTransporteur = "FactTransporteur";
            public const string FactInkoopfactuurnr = "FactInkoopfactuurnr";
            public const string FactFactuurNaar = "FactFactuurNaar";
            public const string FactFactuurNaarSoort = "FactFactuurNaarSoort";
            public const string FactBetaalWijze = "FactBetaalWijze";
            public const string FactMemo = "FactMemo";
            public const string FactLosplaatsId = "FactLosplaatsId";
            public const string FactWerkId = "FactWerkId";
            public const string FactGeprint = "FactGeprint";
            public const string FactIncasso = "FactIncasso";
            public const string FactMailFactuur = "FactMailFactuur";
            public const string Fact_Guid = "Fact_Guid";
            public const string Baliebon_nr = "baliebon_nr";
            public const string Baliebon_uid = "baliebon_uid";
            public const string ThrID = "ThrID";
            public const string ExtDb = "extDb";
            public const string ExtDb_id = "extDb_id";
		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int FactId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FarmId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FarmId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnID
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.UbnID);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.UbnID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactDagBoekId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactDagBoekId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactDagBoekId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactRelatieId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactRelatieId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactRelatieId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactSoort
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactSoort);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactSoort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FactNummer
	    {
			get
	        {
				return base.Getstring(ColumnNamesFACTUUR.FactNummer);
			}
			set
	        {
				base.Setstring(ColumnNamesFACTUUR.FactNummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime FactDatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesFACTUUR.FactDatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesFACTUUR.FactDatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactTransporteur
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactTransporteur);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactTransporteur, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FactInkoopfactuurnr
	    {
			get
	        {
				return base.Getstring(ColumnNamesFACTUUR.FactInkoopfactuurnr);
			}
			set
	        {
				base.Setstring(ColumnNamesFACTUUR.FactInkoopfactuurnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactFactuurNaar
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactFactuurNaar);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactFactuurNaar, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactFactuurNaarSoort
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactFactuurNaarSoort);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactFactuurNaarSoort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactBetaalWijze
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactBetaalWijze);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactBetaalWijze, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FactMemo
	    {
			get
	        {
				return base.Getstring(ColumnNamesFACTUUR.FactMemo);
			}
			set
	        {
				base.Setstring(ColumnNamesFACTUUR.FactMemo, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactLosplaatsId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactLosplaatsId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactLosplaatsId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FactWerkId
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.FactWerkId);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.FactWerkId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactGeprint
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactGeprint);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactGeprint, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactIncasso
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactIncasso);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactIncasso, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte FactMailFactuur
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFACTUUR.FactMailFactuur);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFACTUUR.FactMailFactuur, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Fact_Guid
	    {
			get
	        {
				return base.Getstring(ColumnNamesFACTUUR.Fact_Guid);
			}
			set
	        {
				base.Setstring(ColumnNamesFACTUUR.Fact_Guid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Baliebon_nr
	    {
			get
	        {
				return base.Getstring(ColumnNamesFACTUUR.Baliebon_nr);
			}
			set
	        {
				base.Setstring(ColumnNamesFACTUUR.Baliebon_nr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Baliebon_uid
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.Baliebon_uid);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.Baliebon_uid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ExtDb
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.ExtDb);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.ExtDb, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ExtDb_id
	    {
			get
	        {
				return base.Getint(ColumnNamesFACTUUR.ExtDb_id);
			}
			set
	        {
				base.Setint(ColumnNamesFACTUUR.ExtDb_id, value);
			}
		}

		#endregion
		
	}
}
