
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FEED_REST : DataObject
	{
		public FEED_REST() : base(Database.agrodata)
		{
			UpdateParams = new String[] 
			{
            	"FR_ID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFEED_REST
		{  
            public const string FarmID = "FarmID";
            public const string AniID = "AniID";
            public const string FR_ID = "FR_ID";
            public const string FR_DateTime = "FR_DateTime";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_REST.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_REST.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AniID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_REST.AniID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_REST.AniID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int FR_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_REST.FR_ID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_REST.FR_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime FR_DateTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesFEED_REST.FR_DateTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesFEED_REST.FR_DateTime, value);
			}
		}


		#endregion
		
	}
}
