
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FEEDDATA : DataObject
	{
        [Obsolete("DataObject zonder database tabel")]
        public FEEDDATA()
            : base(Database.temptable)
		{
		}

	
		#region ColumnNames
		public class ColumnNamesFEEDDATA
		{  
            public const string Internalnr = "Internalnr";
            public const string FarmId = "FarmId";
            public const string AniId = "AniId";
            public const string MasterFeedCode = "MasterFeedCode";
            public const string FeedNumber = "FeedNumber";
            public const string FeedRation = "FeedRation";
            public const string FeedRemainder = "FeedRemainder";
 

		}
		#endregion

		#region Properties
	
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesFEEDDATA.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesFEEDDATA.Internalnr, value);
			}
		}

		public int FarmId
	    {
			get
	        {
				return base.Getint(ColumnNamesFEEDDATA.FarmId);
			}
			set
	        {
				base.Setint(ColumnNamesFEEDDATA.FarmId, value);
			}
		}

		public int AniId
	    {
			get
	        {
				return base.Getint(ColumnNamesFEEDDATA.AniId);
			}
			set
	        {
				base.Setint(ColumnNamesFEEDDATA.AniId, value);
			}
		}

		public string MasterFeedCode
	    {
			get
	        {
				return base.Getstring(ColumnNamesFEEDDATA.MasterFeedCode);
			}
			set
	        {
				base.Setstring(ColumnNamesFEEDDATA.MasterFeedCode, value);
			}
		}

		public int FeedNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesFEEDDATA.FeedNumber);
			}
			set
	        {
				base.Setint(ColumnNamesFEEDDATA.FeedNumber, value);
			}
		}

		public double FeedRation
	    {
			get
	        {
				return base.Getdouble(ColumnNamesFEEDDATA.FeedRation);
			}
			set
	        {
				base.Setdouble(ColumnNamesFEEDDATA.FeedRation, value);
			}
		}

		public double FeedRemainder
	    {
			get
	        {
				return base.Getdouble(ColumnNamesFEEDDATA.FeedRemainder);
			}
			set
	        {
				base.Setdouble(ColumnNamesFEEDDATA.FeedRemainder, value);
			}
		}


		#endregion
		
	}
}
