
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FEED_RATION_SETTINGS : DataObject
	{
		public FEED_RATION_SETTINGS() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"UBNid",
            	"AnimalKind_ID",
            	"FR_GroupID",
            	"FR_PhaseNr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFEED_RATION_SETTINGS
		{  
            public const string UBNid = "UBNid";
            public const string AnimalKind_ID = "AnimalKind_ID";
            public const string FR_GroupID = "FR_GroupID";
            public const string FR_PhaseNr = "FR_PhaseNr";
            public const string FR_Kind_of_Phase = "FR_Kind_of_Phase";
            public const string FR_CurveID = "FR_CurveID";
            public const string FR_Day = "FR_Day";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int UBNid
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.UBNid);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.UBNid, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int AnimalKind_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.AnimalKind_ID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.AnimalKind_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FR_GroupID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.FR_GroupID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.FR_GroupID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FR_PhaseNr
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.FR_PhaseNr);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.FR_PhaseNr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)]
        public int FR_Kind_of_Phase
	    {
			get
	        {
                return base.Getint(ColumnNamesFEED_RATION_SETTINGS.FR_Kind_of_Phase);
			}
			set
	        {
                base.Setint(ColumnNamesFEED_RATION_SETTINGS.FR_Kind_of_Phase, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FR_CurveID
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.FR_CurveID);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.FR_CurveID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FR_Day
	    {
			get
	        {
				return base.Getint(ColumnNamesFEED_RATION_SETTINGS.FR_Day);
			}
			set
	        {
				base.Setint(ColumnNamesFEED_RATION_SETTINGS.FR_Day, value);
			}
		}


		#endregion
		
	}
}
