
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FILELOG_EXTERN : DataObject
	{
		public FILELOG_EXTERN() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"FLE_ID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFILELOG_EXTERN
		{  
            public const string FLE_ID = "FLE_ID";
            public const string FLE_Internalnr = "FLE_Internalnr";
            public const string FLE_FarmNumber = "FLE_FarmNumber";
            public const string FLE_NameFile = "FLE_NameFile";
            public const string FLE_Kind = "FLE_Kind";
            public const string FLE_RemarkID = "FLE_RemarkID";
            public const string FLE_DateTime = "FLE_DateTime";
            public const string FLE_Lifenumber = "FLE_Lifenumber";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int FLE_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesFILELOG_EXTERN.FLE_ID);
			}
			set
	        {
				base.Setint(ColumnNamesFILELOG_EXTERN.FLE_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FLE_Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesFILELOG_EXTERN.FLE_Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesFILELOG_EXTERN.FLE_Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FLE_FarmNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesFILELOG_EXTERN.FLE_FarmNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesFILELOG_EXTERN.FLE_FarmNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FLE_NameFile
	    {
			get
	        {
				return base.Getstring(ColumnNamesFILELOG_EXTERN.FLE_NameFile);
			}
			set
	        {
				base.Setstring(ColumnNamesFILELOG_EXTERN.FLE_NameFile, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FLE_Kind
	    {
			get
	        {
				return base.Getint(ColumnNamesFILELOG_EXTERN.FLE_Kind);
			}
			set
	        {
				base.Setint(ColumnNamesFILELOG_EXTERN.FLE_Kind, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FLE_RemarkID
	    {
			get
	        {
				return base.Getint(ColumnNamesFILELOG_EXTERN.FLE_RemarkID);
			}
			set
	        {
				base.Setint(ColumnNamesFILELOG_EXTERN.FLE_RemarkID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime FLE_DateTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesFILELOG_EXTERN.FLE_DateTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesFILELOG_EXTERN.FLE_DateTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FLE_Lifenumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesFILELOG_EXTERN.FLE_Lifenumber);
			}
			set
	        {
				base.Setstring(ColumnNamesFILELOG_EXTERN.FLE_Lifenumber, value);
			}
		}


		#endregion
		
	}
}
