
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class FTPLIST : DataObject
	{
		public FTPLIST() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"FtpNumber"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesFTPLIST
		{  
            public const string FtpNumber = "FtpNumber";
            public const string FtpHostName = "FtpHostName";
            public const string PassiveMode = "PassiveMode";
            public const string FtpDescription = "FtpDescription";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FtpNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesFTPLIST.FtpNumber);
			}
			set
	        {
				base.Setint(ColumnNamesFTPLIST.FtpNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FtpHostName
	    {
			get
	        {
				return base.Getstring(ColumnNamesFTPLIST.FtpHostName);
			}
			set
	        {
				base.Setstring(ColumnNamesFTPLIST.FtpHostName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte PassiveMode
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesFTPLIST.PassiveMode);
			}
			set
	        {
				base.Setsbyte(ColumnNamesFTPLIST.PassiveMode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FtpDescription
	    {
			get
	        {
				return base.Getstring(ColumnNamesFTPLIST.FtpDescription);
			}
			set
	        {
				base.Setstring(ColumnNamesFTPLIST.FtpDescription, value);
			}
		}


		#endregion
		
	}
}
