
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class GBPERCELEN : DataObject
	{
		public GBPERCELEN() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"Farmid",
            	"GBperceelid"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesGBPERCELEN
		{  
            public const string Farmid = "Farmid";
            public const string GBperceelid = "GBperceelid";
            public const string GBvolgnr = "GBvolgnr";
            public const string GBbegindatum = "GBbegindatum";
            public const string GBeinddatum = "GBeinddatum";
            public const string GBoppervlak = "GBoppervlak";
            public const string GBgewascode = "GBgewascode";
            public const string GBgebruikscode = "GBgebruikscode";
            public const string GBstatusGebruik = "GBstatusGebruik";
            public const string GBperceeslbron = "GBperceeslbron";
            public const string GBwijzigdatum = "GBwijzigdatum";
            public const string GBformuliernr = "GBformuliernr";
            public const string GBcommunicatienr = "GBcommunicatienr";
            public const string Actief = "Actief";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Farmid
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.Farmid);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.Farmid, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int GBperceelid
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.GBperceelid);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.GBperceelid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int GBvolgnr
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.GBvolgnr);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.GBvolgnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime GBbegindatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesGBPERCELEN.GBbegindatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesGBPERCELEN.GBbegindatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime GBeinddatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesGBPERCELEN.GBeinddatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesGBPERCELEN.GBeinddatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double GBoppervlak
	    {
			get
	        {
				return base.Getdouble(ColumnNamesGBPERCELEN.GBoppervlak);
			}
			set
	        {
				base.Setdouble(ColumnNamesGBPERCELEN.GBoppervlak, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int GBgewascode
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.GBgewascode);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.GBgewascode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int GBgebruikscode
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.GBgebruikscode);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.GBgebruikscode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string GBstatusGebruik
	    {
			get
	        {
				return base.Getstring(ColumnNamesGBPERCELEN.GBstatusGebruik);
			}
			set
	        {
				base.Setstring(ColumnNamesGBPERCELEN.GBstatusGebruik, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string GBperceeslbron
	    {
			get
	        {
				return base.Getstring(ColumnNamesGBPERCELEN.GBperceeslbron);
			}
			set
	        {
				base.Setstring(ColumnNamesGBPERCELEN.GBperceeslbron, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime GBwijzigdatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesGBPERCELEN.GBwijzigdatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesGBPERCELEN.GBwijzigdatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string GBformuliernr
	    {
			get
	        {
				return base.Getstring(ColumnNamesGBPERCELEN.GBformuliernr);
			}
			set
	        {
				base.Setstring(ColumnNamesGBPERCELEN.GBformuliernr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string GBcommunicatienr
	    {
			get
	        {
				return base.Getstring(ColumnNamesGBPERCELEN.GBcommunicatienr);
			}
			set
	        {
				base.Setstring(ColumnNamesGBPERCELEN.GBcommunicatienr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Actief
	    {
			get
	        {
				return base.Getint(ColumnNamesGBPERCELEN.Actief);
			}
			set
	        {
				base.Setint(ColumnNamesGBPERCELEN.Actief, value);
			}
		}


		#endregion
		
	}
}
