
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class IMPFILE2 : DataObject
	{
		public IMPFILE2() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesIMPFILE2
		{  
            public const string ImpFileID = "ImpFileID";
            public const string Internalnr = "Internalnr";
            public const string EventID = "EventID";
            public const string MovID = "MovID";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ImpFileID
	    {
			get
	        {
				return base.Getint(ColumnNamesIMPFILE2.ImpFileID);
			}
			set
	        {
				base.Setint(ColumnNamesIMPFILE2.ImpFileID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesIMPFILE2.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesIMPFILE2.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int EventID
	    {
			get
	        {
				return base.Getint(ColumnNamesIMPFILE2.EventID);
			}
			set
	        {
				base.Setint(ColumnNamesIMPFILE2.EventID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MovID
	    {
			get
	        {
				return base.Getint(ColumnNamesIMPFILE2.MovID);
			}
			set
	        {
				base.Setint(ColumnNamesIMPFILE2.MovID, value);
			}
		}


		#endregion
		
	}
}
