
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class KEURING_TYPE : DataObject
	{
		public KEURING_TYPE() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"KtId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesKEURING_TYPE
		{  
            public const string KtId = "ktId";
            public const string KtNaam = "ktNaam";
            public const string KtProgramId = "ktProgramId";
            public const string KtHidden = "ktHidden";
            public const string Kt_ExtSoort = "kt_ExtSoort";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int KtId
	    {
			get
	        {
				return base.Getint(ColumnNamesKEURING_TYPE.KtId);
			}
			set
	        {
				base.Setint(ColumnNamesKEURING_TYPE.KtId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string KtNaam
	    {
			get
	        {
				return base.Getstring(ColumnNamesKEURING_TYPE.KtNaam);
			}
			set
	        {
				base.Setstring(ColumnNamesKEURING_TYPE.KtNaam, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int KtProgramId
	    {
			get
	        {
				return base.Getint(ColumnNamesKEURING_TYPE.KtProgramId);
			}
			set
	        {
				base.Setint(ColumnNamesKEURING_TYPE.KtProgramId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte KtHidden
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesKEURING_TYPE.KtHidden);
			}
			set
	        {
				base.Setsbyte(ColumnNamesKEURING_TYPE.KtHidden, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)]
        public int kt_ExtSoort
	    {
			get
	        {
				return base.Getint(ColumnNamesKEURING_TYPE.Kt_ExtSoort);
			}
			set
	        {
				base.Setint(ColumnNamesKEURING_TYPE.Kt_ExtSoort, value);
			}
		}


		#endregion
		
	}
}
