
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LABERRKI : DataObject
	{
		public LABERRKI() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLABERRKI
		{  
            public const string Country = "Country";
            public const string ErrorKind = "ErrorKind";
            public const string ErrorNumber = "ErrorNumber";
            public const string ErrorDescription = "ErrorDescription";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Country
	    {
			get
	        {
				return base.Getint(ColumnNamesLABERRKI.Country);
			}
			set
	        {
				base.Setint(ColumnNamesLABERRKI.Country, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ErrorKind
	    {
			get
	        {
				return base.Getint(ColumnNamesLABERRKI.ErrorKind);
			}
			set
	        {
				base.Setint(ColumnNamesLABERRKI.ErrorKind, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ErrorNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesLABERRKI.ErrorNumber);
			}
			set
	        {
				base.Setint(ColumnNamesLABERRKI.ErrorNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ErrorDescription
	    {
			get
	        {
				return base.Getstring(ColumnNamesLABERRKI.ErrorDescription);
			}
			set
	        {
				base.Setstring(ColumnNamesLABERRKI.ErrorDescription, value);
			}
		}


		#endregion
		
	}
}
