
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LABMINAS : DataObject
	{
		public LABMINAS() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLABMINAS
		{  
            public const string LabCountry = "LabCountry";
            public const string LabKind = "LabKind";
            public const string LabId = "LabId";
            public const string LabLabel = "LabLabel";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LabCountry
	    {
			get
	        {
				return base.Getint(ColumnNamesLABMINAS.LabCountry);
			}
			set
	        {
				base.Setint(ColumnNamesLABMINAS.LabCountry, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LabKind
	    {
			get
	        {
				return base.Getint(ColumnNamesLABMINAS.LabKind);
			}
			set
	        {
				base.Setint(ColumnNamesLABMINAS.LabKind, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LabId
	    {
			get
	        {
				return base.Getint(ColumnNamesLABMINAS.LabId);
			}
			set
	        {
				base.Setint(ColumnNamesLABMINAS.LabId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LabLabel
	    {
			get
	        {
				return base.Getstring(ColumnNamesLABMINAS.LabLabel);
			}
			set
	        {
				base.Setstring(ColumnNamesLABMINAS.LabLabel, value);
			}
		}


		#endregion
		
	}
}
