
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LIFENR : DataObject
	{
		public LIFENR() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"LifId",
            	"FarmNumber",
            	"owner_ThrID",
            	"Program",
            	"LifCountrycode",
            	"LifLifenr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLIFENR
		{  
            public const string LifId = "LifId";
            public const string FarmNumber = "FarmNumber";
            public const string owner_ThrID = "owner_ThrID";
            public const string Program = "Program";
            public const string LifCountrycode = "LifCountrycode";
            public const string LifLifenr = "LifLifenr";
            public const string LifSort = "LifSort";
            public const string Lev_ThrID = "Lev_ThrID";
            public const string Oormerktype = "Oormerktype";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int LifId
	    {
			get
	        {
				return base.Getint(ColumnNamesLIFENR.LifId);
			}
			set
	        {
				base.Setint(ColumnNamesLIFENR.LifId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public string FarmNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesLIFENR.FarmNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesLIFENR.FarmNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int owner_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesLIFENR.owner_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesLIFENR.owner_ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Program
	    {
			get
	        {
				return base.Getint(ColumnNamesLIFENR.Program);
			}
			set
	        {
				base.Setint(ColumnNamesLIFENR.Program, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public string LifCountrycode
	    {
			get
	        {
				return base.Getstring(ColumnNamesLIFENR.LifCountrycode);
			}
			set
	        {
				base.Setstring(ColumnNamesLIFENR.LifCountrycode, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public string LifLifenr
	    {
			get
	        {
				return base.Getstring(ColumnNamesLIFENR.LifLifenr);
			}
			set
	        {
				base.Setstring(ColumnNamesLIFENR.LifLifenr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LifSort
	    {
			get
	        {
				return base.Getstring(ColumnNamesLIFENR.LifSort);
			}
			set
	        {
				base.Setstring(ColumnNamesLIFENR.LifSort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Lev_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesLIFENR.Lev_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesLIFENR.Lev_ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Oormerktype
	    {
			get
	        {
				return base.Getstring(ColumnNamesLIFENR.Oormerktype);
			}
			set
	        {
				base.Setstring(ColumnNamesLIFENR.Oormerktype, value);
			}
		}


		#endregion
		
	}
}
