
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LISCATEG : DataObject
	{
		public LISCATEG() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"ListId",
            	"CategorieId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLISCATEG
		{  
            public const string ListId = "ListId";
            public const string CategorieId = "CategorieId";
            public const string UseCategorie = "UseCategorie";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ListId
	    {
			get
	        {
				return base.Getint(ColumnNamesLISCATEG.ListId);
			}
			set
	        {
				base.Setint(ColumnNamesLISCATEG.ListId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int CategorieId
	    {
			get
	        {
				return base.Getint(ColumnNamesLISCATEG.CategorieId);
			}
			set
	        {
				base.Setint(ColumnNamesLISCATEG.CategorieId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte UseCategorie
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesLISCATEG.UseCategorie);
			}
			set
	        {
				base.Setsbyte(ColumnNamesLISCATEG.UseCategorie, value);
			}
		}


		#endregion
		
	}
}
