
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LOG_LOGIN : DataObject
	{
		public LOG_LOGIN() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLOG_LOGIN
		{  
            public const string LogThrId = "LogThrId";
            public const string LogUbnId = "LogUbnId";
            public const string LogDate = "LogDate";
            public const string LogIpAdress = "LogIpAdress";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LogThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOG_LOGIN.LogThrId);
			}
			set
	        {
				base.Setint(ColumnNamesLOG_LOGIN.LogThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LogUbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOG_LOGIN.LogUbnId);
			}
			set
	        {
				base.Setint(ColumnNamesLOG_LOGIN.LogUbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime LogDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesLOG_LOGIN.LogDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesLOG_LOGIN.LogDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LogIpAdress
	    {
			get
	        {
				return base.Getstring(ColumnNamesLOG_LOGIN.LogIpAdress);
			}
			set
	        {
				base.Setstring(ColumnNamesLOG_LOGIN.LogIpAdress, value);
			}
		}


		#endregion
		
	}
}
