
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class LOSS : DataObject
	{
		public LOSS() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"MovId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesLOSS
		{  
            public const string AniId = "AniId";
            public const string MovId = "MovId";
            public const string LosRegisteryNumber = "LosRegisteryNumber";
            public const string LosDiseaseId = "LosDiseaseId";
            public const string LosDiseasesubId = "LosDiseasesubId";
            public const string LosWeight = "LosWeight";
            public const string LosReason = "LosReason";
            public const string LosVersienrVertrekluik = "LosVersienrVertrekluik";
            public const string LosMeldnummer = "LosMeldnummer";
            public const string LosTransporteur = "LosTransporteur";
		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AniId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.AniId);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.AniId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int MovId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.MovId);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.MovId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LosRegisteryNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesLOSS.LosRegisteryNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesLOSS.LosRegisteryNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LosDiseaseId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.LosDiseaseId);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.LosDiseaseId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LosDiseasesubId
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.LosDiseasesubId);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.LosDiseasesubId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double LosWeight
	    {
			get
	        {
				return base.Getdouble(ColumnNamesLOSS.LosWeight);
			}
			set
	        {
				base.Setdouble(ColumnNamesLOSS.LosWeight, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LosReason
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.LosReason);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.LosReason, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LosVersienrVertrekluik
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.LosVersienrVertrekluik);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.LosVersienrVertrekluik, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LosMeldnummer
	    {
			get
	        {
				return base.Getstring(ColumnNamesLOSS.LosMeldnummer);
			}
			set
	        {
				base.Setstring(ColumnNamesLOSS.LosMeldnummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LosTransporteur
	    {
			get
	        {
				return base.Getint(ColumnNamesLOSS.LosTransporteur);
			}
			set
	        {
				base.Setint(ColumnNamesLOSS.LosTransporteur, value);
			}
		}



		#endregion
		
	}
}
