
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MEDICINE : DataObject
	{
		public MEDICINE() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"MedId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMEDICINE
		{  
            public const string MedId = "MedId";
            public const string MedName = "MedName";
            public const string MedActiveProduct = "MedActiveProduct";
            public const string MedDaysWaitingMilk = "MedDaysWaitingMilk";
            public const string MedDaysWaitingMeat = "MedDaysWaitingMeat";
            public const string MedUnit = "MedUnit";
            public const string MedUnitVolume = "MedUnitVolume";
            public const string MedPrice = "MedPrice";
            public const string MedPriceEuro = "MedPriceEuro";
            public const string MedPriceUnit = "MedPriceUnit";
            public const string MedCurrencyEuro = "MedCurrencyEuro";
            public const string MedHoursWaitingMilk = "MedHoursWaitingMilk";
            public const string MedHoursWaitingMeat = "MedHoursWaitingMeat";
            public const string MedCode = "MedCode";
            public const string MedBatchNumber = "MedBatchNumber";
            public const string MedThrId = "MedThrId";
            public const string MedFunction = "MedFunction";
            public const string MedReg = "MedReg";
            public const string MedUDD = "MedUDD";
            public const string MedDisGroup = "MedDisGroup";
            public const string MedDaysTreat = "MedDaysTreat";
            public const string MedApply = "MedApply";
            public const string MedPreference = "MedPreference";
            public const string MedHoursRepeat = "MedHoursRepeat";
            public const string MedMP3file = "MedMP3file";
            public const string MedAmountPerXKg = "MedAmountPerXKg";
            public const string MedKgAliveWeight = "MedKgAliveWeight";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int MedId
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedId);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MedName
	    {
			get
	        {
				return base.Getstring(ColumnNamesMEDICINE.MedName);
			}
			set
	        {
				base.Setstring(ColumnNamesMEDICINE.MedName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MedActiveProduct
	    {
			get
	        {
				return base.Getstring(ColumnNamesMEDICINE.MedActiveProduct);
			}
			set
	        {
				base.Setstring(ColumnNamesMEDICINE.MedActiveProduct, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedDaysWaitingMilk
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedDaysWaitingMilk);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedDaysWaitingMilk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedDaysWaitingMeat
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedDaysWaitingMeat);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedDaysWaitingMeat, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedUnit
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedUnit);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedUnit, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedUnitVolume
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedUnitVolume);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedUnitVolume, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double MedPrice
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEDICINE.MedPrice);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEDICINE.MedPrice, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double MedPriceEuro
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEDICINE.MedPriceEuro);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEDICINE.MedPriceEuro, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedPriceUnit
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedPriceUnit);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedPriceUnit, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte MedCurrencyEuro
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesMEDICINE.MedCurrencyEuro);
			}
			set
	        {
				base.Setsbyte(ColumnNamesMEDICINE.MedCurrencyEuro, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedHoursWaitingMilk
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedHoursWaitingMilk);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedHoursWaitingMilk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedHoursWaitingMeat
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedHoursWaitingMeat);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedHoursWaitingMeat, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MedCode
	    {
			get
	        {
				return base.Getstring(ColumnNamesMEDICINE.MedCode);
			}
			set
	        {
				base.Setstring(ColumnNamesMEDICINE.MedCode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MedBatchNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesMEDICINE.MedBatchNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesMEDICINE.MedBatchNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedThrId);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedFunction
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedFunction);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedFunction, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte MedReg
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesMEDICINE.MedReg);
			}
			set
	        {
				base.Setsbyte(ColumnNamesMEDICINE.MedReg, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte MedUDD
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesMEDICINE.MedUDD);
			}
			set
	        {
				base.Setsbyte(ColumnNamesMEDICINE.MedUDD, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedDisGroup
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedDisGroup);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedDisGroup, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedDaysTreat
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedDaysTreat);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedDaysTreat, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedApply
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedApply);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedApply, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedPreference
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedPreference);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedPreference, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MedHoursRepeat
	    {
			get
	        {
				return base.Getint(ColumnNamesMEDICINE.MedHoursRepeat);
			}
			set
	        {
				base.Setint(ColumnNamesMEDICINE.MedHoursRepeat, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MedMP3file
	    {
			get
	        {
				return base.Getstring(ColumnNamesMEDICINE.MedMP3file);
			}
			set
	        {
				base.Setstring(ColumnNamesMEDICINE.MedMP3file, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double MedAmountPerXKg
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEDICINE.MedAmountPerXKg);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEDICINE.MedAmountPerXKg, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double MedKgAliveWeight
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEDICINE.MedKgAliveWeight);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEDICINE.MedKgAliveWeight, value);
			}
		}


		#endregion
		
	}
}
