
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MEIEREN : DataObject
	{
		public MEIEREN() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"Jaar",
            	"SoortEi"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMEIEREN
		{  
            public const string Jaar = "Jaar";
            public const string SoortEi = "SoortEi";
            public const string KgNperKg = "KgNperKg";
            public const string KgP2O5perKg = "KgP2O5perKg";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Jaar
	    {
			get
	        {
				return base.Getint(ColumnNamesMEIEREN.Jaar);
			}
			set
	        {
				base.Setint(ColumnNamesMEIEREN.Jaar, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int SoortEi
	    {
			get
	        {
				return base.Getint(ColumnNamesMEIEREN.SoortEi);
			}
			set
	        {
				base.Setint(ColumnNamesMEIEREN.SoortEi, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgNperKg
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEIEREN.KgNperKg);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEIEREN.KgNperKg, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgP2O5perKg
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMEIEREN.KgP2O5perKg);
			}
			set
	        {
				base.Setdouble(ColumnNamesMEIEREN.KgP2O5perKg, value);
			}
		}


		#endregion
		
	}
}
