
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MELK_MINERALEN : DataObject
	{
		public MELK_MINERALEN() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMELK_MINERALEN
		{  
            public const string UbnId = "UbnId";
            public const string TankNr = "TankNr";
            public const string ControlDate = "ControlDate";
            public const string Buisnummer = "Buisnummer";
            public const string Cu = "Cu";
            public const string Mg = "Mg";
            public const string Se = "Se";
            public const string Zn = "Zn";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MINERALEN.UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MINERALEN.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int TankNr
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MINERALEN.TankNr);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MINERALEN.TankNr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ControlDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesMELK_MINERALEN.ControlDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesMELK_MINERALEN.ControlDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Buisnummer
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MINERALEN.Buisnummer);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MINERALEN.Buisnummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Cu
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMELK_MINERALEN.Cu);
			}
			set
	        {
				base.Setdouble(ColumnNamesMELK_MINERALEN.Cu, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public decimal Mg
	    {
			get
	        {
				return base.Getdecimal(ColumnNamesMELK_MINERALEN.Mg);
			}
			set
	        {
				base.Setdecimal(ColumnNamesMELK_MINERALEN.Mg, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public decimal Se
	    {
			get
	        {
				return base.Getdecimal(ColumnNamesMELK_MINERALEN.Se);
			}
			set
	        {
				base.Setdecimal(ColumnNamesMELK_MINERALEN.Se, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public decimal Zn
	    {
			get
	        {
				return base.Getdecimal(ColumnNamesMELK_MINERALEN.Zn);
			}
			set
	        {
				base.Setdecimal(ColumnNamesMELK_MINERALEN.Zn, value);
			}
		}


		#endregion
		
	}
}
