
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MELK_MASTITIS : DataObject
	{
		public MELK_MASTITIS() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMELK_MASTITIS
		{  
            public const string UbnId = "UbnId";
            public const string Tanknr = "Tanknr";
            public const string ControlDate = "ControlDate";
            public const string Bacterie = "Bacterie";
            public const string Relatieve_kwantiteit = "Relatieve_kwantiteit";
            public const string Proportie = "Proportie";
            public const string Ct = "Ct";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MASTITIS.UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MASTITIS.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Tanknr
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MASTITIS.Tanknr);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MASTITIS.Tanknr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ControlDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesMELK_MASTITIS.ControlDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesMELK_MASTITIS.ControlDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Bacterie
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_MASTITIS.Bacterie);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_MASTITIS.Bacterie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Relatieve_kwantiteit
	    {
			get
	        {
				return base.Getstring(ColumnNamesMELK_MASTITIS.Relatieve_kwantiteit);
			}
			set
	        {
				base.Setstring(ColumnNamesMELK_MASTITIS.Relatieve_kwantiteit, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Proportie
	    {
			get
	        {
				return base.Getstring(ColumnNamesMELK_MASTITIS.Proportie);
			}
			set
	        {
				base.Setstring(ColumnNamesMELK_MASTITIS.Proportie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public decimal Ct
	    {
			get
	        {
				return base.Getdecimal(ColumnNamesMELK_MASTITIS.Ct);
			}
			set
	        {
				base.Setdecimal(ColumnNamesMELK_MASTITIS.Ct, value);
			}
		}


		#endregion
		
	}
}
