
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MELK_DIERZIEKTE : DataObject
	{
		public MELK_DIERZIEKTE() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMELK_DIERZIEKTE
		{  
            public const string UbnId = "UbnId";
            public const string Tanknr = "Tanknr";
            public const string ControlDate = "ControlDate";
            public const string BVD = "BVD";
            public const string Salmonella = "Salmonella";
            public const string ParaTB = "ParaTB";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_DIERZIEKTE.UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_DIERZIEKTE.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Tanknr
	    {
			get
	        {
				return base.Getint(ColumnNamesMELK_DIERZIEKTE.Tanknr);
			}
			set
	        {
				base.Setint(ColumnNamesMELK_DIERZIEKTE.Tanknr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ControlDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesMELK_DIERZIEKTE.ControlDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesMELK_DIERZIEKTE.ControlDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double BVD
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMELK_DIERZIEKTE.BVD);
			}
			set
	        {
				base.Setdouble(ColumnNamesMELK_DIERZIEKTE.BVD, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Salmonella
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMELK_DIERZIEKTE.Salmonella);
			}
			set
	        {
				base.Setdouble(ColumnNamesMELK_DIERZIEKTE.Salmonella, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ParaTB
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMELK_DIERZIEKTE.ParaTB);
			}
			set
	        {
				base.Setdouble(ColumnNamesMELK_DIERZIEKTE.ParaTB, value);
			}
		}


		#endregion
		
	}
}
