
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MIDSTOCK : DataObject
	{
		public MIDSTOCK() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"MSstockid",
            	"FarmId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMIDSTOCK
		{  
            public const string MSstockid = "MSstockid";
            public const string FarmId = "FarmId";
            public const string MSMiddelId = "MSMiddelId";
            public const string MSdatum = "MSdatum";
            public const string MSToelatingsnummer = "MSToelatingsnummer";
            public const string MSEenheid = "MSEenheid";
            public const string MSHoeveelheid = "MSHoeveelheid";
            public const string MSmutatie = "MSmutatie";
            public const string MSactid = "MSactid";
            public const string MSremark = "MSremark";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int MSstockid
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.MSstockid);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.MSstockid, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FarmId
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.FarmId);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.FarmId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MSMiddelId
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.MSMiddelId);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.MSMiddelId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime MSdatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesMIDSTOCK.MSdatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesMIDSTOCK.MSdatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MSToelatingsnummer
	    {
			get
	        {
				return base.Getstring(ColumnNamesMIDSTOCK.MSToelatingsnummer);
			}
			set
	        {
				base.Setstring(ColumnNamesMIDSTOCK.MSToelatingsnummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MSEenheid
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.MSEenheid);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.MSEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double MSHoeveelheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMIDSTOCK.MSHoeveelheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesMIDSTOCK.MSHoeveelheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MSmutatie
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.MSmutatie);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.MSmutatie, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int MSactid
	    {
			get
	        {
				return base.Getint(ColumnNamesMIDSTOCK.MSactid);
			}
			set
	        {
				base.Setint(ColumnNamesMIDSTOCK.MSactid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string MSremark
	    {
			get
	        {
				return base.Getstring(ColumnNamesMIDSTOCK.MSremark);
			}
			set
	        {
				base.Setstring(ColumnNamesMIDSTOCK.MSremark, value);
			}
		}


		#endregion
		
	}
}
