
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MRUWVOER : DataObject
	{
		public MRUWVOER() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"Jaar",
            	"Gewas"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMRUWVOER
		{  
            public const string Jaar = "Jaar";
            public const string Gewas = "Gewas";
            public const string TonDsPerHa = "TonDsPerHa";
            public const string TonProductPerHa = "TonProductPerHa";
            public const string KgNperTonDs = "KgNperTonDs";
            public const string KgP2O5perTonDs = "KgP2O5perTonDs";
            public const string KgNperTonVers = "KgNperTonVers";
            public const string KgP2O5perTonVers = "KgP2O5perTonVers";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Jaar
	    {
			get
	        {
				return base.Getint(ColumnNamesMRUWVOER.Jaar);
			}
			set
	        {
				base.Setint(ColumnNamesMRUWVOER.Jaar, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Gewas
	    {
			get
	        {
				return base.Getint(ColumnNamesMRUWVOER.Gewas);
			}
			set
	        {
				base.Setint(ColumnNamesMRUWVOER.Gewas, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double TonDsPerHa
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.TonDsPerHa);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.TonDsPerHa, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double TonProductPerHa
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.TonProductPerHa);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.TonProductPerHa, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgNperTonDs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.KgNperTonDs);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.KgNperTonDs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgP2O5perTonDs
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.KgP2O5perTonDs);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.KgP2O5perTonDs, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgNperTonVers
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.KgNperTonVers);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.KgNperTonVers, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double KgP2O5perTonVers
	    {
			get
	        {
				return base.Getdouble(ColumnNamesMRUWVOER.KgP2O5perTonVers);
			}
			set
	        {
				base.Setdouble(ColumnNamesMRUWVOER.KgP2O5perTonVers, value);
			}
		}


		#endregion
		
	}
}
