
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class MUTA_VOER_LOG : DataObject
	{
		public MUTA_VOER_LOG() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesMUTA_VOER_LOG
		{  
            public const string Mv_ThrID = "mv_ThrID";
            public const string Mv_KvK = "mv_KvK";
            public const string Mv_BRS = "mv_BRS";
            public const string Mv_Afnemer_ThrID = "mv_Afnemer_ThrID";
            public const string Mv_Afnemer_BRS = "mv_Afnemer_BRS";
            public const string Mv_MinasCategory = "mv_MinasCategory";
            public const string Mv_Diersoort = "mv_Diersoort";
            public const string Mv_Totaal_KG = "mv_Totaal_KG";
            public const string Mv_Totaal_P205 = "mv_Totaal_P205";
            public const string Mv_Totaal_N = "mv_Totaal_N";
            public const string Mv_datum = "mv_datum";
            public const string Mv_Afnemer_Companyname = "mv_Afnemer_Companyname";
            public const string Mv_Afnemer_Adres = "mv_Afnemer_Adres";
            public const string Mv_Afnemer_Huisnr = "mv_Afnemer_Huisnr";
            public const string Mv_Afnemer_ZipCode = "mv_Afnemer_ZipCode";
            public const string Mv_Afnemer_City = "mv_Afnemer_City";
            public const string Mv_Afnemer_KvK = "mv_Afnemer_KvK";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Mv_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesMUTA_VOER_LOG.Mv_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesMUTA_VOER_LOG.Mv_ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_KvK
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_KvK);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_KvK, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_BRS
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_BRS);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_BRS, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Mv_Afnemer_ThrID
	    {
			get
	        {
				return base.Getint(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_ThrID);
			}
			set
	        {
				base.Setint(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_ThrID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_BRS
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_BRS);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_BRS, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Mv_MinasCategory
	    {
			get
	        {
				return base.Getint(ColumnNamesMUTA_VOER_LOG.Mv_MinasCategory);
			}
			set
	        {
				base.Setint(ColumnNamesMUTA_VOER_LOG.Mv_MinasCategory, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Mv_Diersoort
	    {
			get
	        {
				return base.Getint(ColumnNamesMUTA_VOER_LOG.Mv_Diersoort);
			}
			set
	        {
				base.Setint(ColumnNamesMUTA_VOER_LOG.Mv_Diersoort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Mv_Totaal_KG
	    {
			get
	        {
				return base.Getfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_KG);
			}
			set
	        {
				base.Setfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_KG, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Mv_Totaal_P205
	    {
			get
	        {
				return base.Getfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_P205);
			}
			set
	        {
				base.Setfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_P205, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public float Mv_Totaal_N
	    {
			get
	        {
				return base.Getfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_N);
			}
			set
	        {
				base.Setfloat(ColumnNamesMUTA_VOER_LOG.Mv_Totaal_N, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Mv_datum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesMUTA_VOER_LOG.Mv_datum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesMUTA_VOER_LOG.Mv_datum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_Companyname
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Companyname);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Companyname, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_Adres
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Adres);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Adres, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_Huisnr
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Huisnr);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_Huisnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_ZipCode
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_ZipCode);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_ZipCode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_City
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_City);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_City, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Mv_Afnemer_KvK
	    {
			get
	        {
				return base.Getstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_KvK);
			}
			set
	        {
				base.Setstring(ColumnNamesMUTA_VOER_LOG.Mv_Afnemer_KvK, value);
			}
		}


		#endregion
		
	}
}
