
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class PROCESCOMPUTER : DataObject
	{
		public PROCESCOMPUTER() : base(Database.agrologs)
		{
			UpdateParams = new String[] 
			{
            	"LogId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesPROCESCOMPUTER
		{  
            public const string LogId = "logId";
            public const string LogticketId = "logticketId";
            public const string LogBegindatetime = "logBegindatetime";
            public const string LogEnddatetime = "logEnddatetime";
            public const string LogResult = "logResult";
            public const string PcType = "pcType";
            public const string PcVersion = "pcVersion";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public uint LogId
	    {
			get
	        {
				return base.Getuint(ColumnNamesPROCESCOMPUTER.LogId);
			}
			set
	        {
				base.Setuint(ColumnNamesPROCESCOMPUTER.LogId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LogticketId
	    {
			get
	        {
				return base.Getint(ColumnNamesPROCESCOMPUTER.LogticketId);
			}
			set
	        {
				base.Setint(ColumnNamesPROCESCOMPUTER.LogticketId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime LogBegindatetime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesPROCESCOMPUTER.LogBegindatetime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesPROCESCOMPUTER.LogBegindatetime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime LogEnddatetime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesPROCESCOMPUTER.LogEnddatetime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesPROCESCOMPUTER.LogEnddatetime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte LogResult
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesPROCESCOMPUTER.LogResult);
			}
			set
	        {
				base.Setsbyte(ColumnNamesPROCESCOMPUTER.LogResult, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte PcType
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesPROCESCOMPUTER.PcType);
			}
			set
	        {
				base.Setsbyte(ColumnNamesPROCESCOMPUTER.PcType, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string PcVersion
	    {
			get
	        {
				return base.Getstring(ColumnNamesPROCESCOMPUTER.PcVersion);
			}
			set
	        {
				base.Setstring(ColumnNamesPROCESCOMPUTER.PcVersion, value);
			}
		}


		#endregion
		
	}
}
