
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class PROJECT_MEMBER : DataObject
	{
		public PROJECT_MEMBER() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{
            	"ProjId",
            	"ThrId",
            	"UbnId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesPROJECT_MEMBER
		{  
            public const string ProjId = "ProjId";
            public const string ThrId = "ThrId";
            public const string UbnId = "UbnId";
            public const string Pm_access = "Pm_access";
            public const string INS = "INS";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ProjId
	    {
			get
	        {
				return base.Getint(ColumnNamesPROJECT_MEMBER.ProjId);
			}
			set
	        {
				base.Setint(ColumnNamesPROJECT_MEMBER.ProjId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesPROJECT_MEMBER.ThrId);
			}
			set
	        {
				base.Setint(ColumnNamesPROJECT_MEMBER.ThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesPROJECT_MEMBER.UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesPROJECT_MEMBER.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Pm_access
	    {
			get
	        {
				return base.Getint(ColumnNamesPROJECT_MEMBER.Pm_access);
			}
			set
	        {
				base.Setint(ColumnNamesPROJECT_MEMBER.Pm_access, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime INS
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesPROJECT_MEMBER.INS);
			}
			set
	        {
				base.SetDateTime(ColumnNamesPROJECT_MEMBER.INS, value);
			}
		}


		#endregion
		
	}
}
