
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class PSKEN : DataObject
	{
		public PSKEN() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"DDnumber"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesPSKEN
		{  
            public const string DDnumber = "DDnumber";
            public const string fd_Length = "fd_Length";
            public const string Digits = "Digits";
            public const string Spread = "Spread";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int DDnumber
	    {
			get
	        {
				return base.Getint(ColumnNamesPSKEN.DDnumber);
			}
			set
	        {
				base.Setint(ColumnNamesPSKEN.DDnumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Fd_Length
	    {
			get
	        {
				return base.Getint(ColumnNamesPSKEN.fd_Length);
			}
			set
	        {
				base.Setint(ColumnNamesPSKEN.fd_Length, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Digits
	    {
			get
	        {
				return base.Getint(ColumnNamesPSKEN.Digits);
			}
			set
	        {
				base.Setint(ColumnNamesPSKEN.Digits, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Spread
	    {
			get
	        {
				return base.Getdouble(ColumnNamesPSKEN.Spread);
			}
			set
	        {
				base.Setdouble(ColumnNamesPSKEN.Spread, value);
			}
		}


		#endregion
		
	}
}
