
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class PSKENTV : DataObject
	{
		public PSKENTV() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"DDNumber"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesPSKENTV
		{  
            public const string DDNumber = "DDNumber";
            public const string TargetValue = "TargetValue";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int DDNumber
	    {
			get
	        {
				return base.Getint(ColumnNamesPSKENTV.DDNumber);
			}
			set
	        {
				base.Setint(ColumnNamesPSKENTV.DDNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double TargetValue
	    {
			get
	        {
				return base.Getdouble(ColumnNamesPSKENTV.TargetValue);
			}
			set
	        {
				base.Setdouble(ColumnNamesPSKENTV.TargetValue, value);
			}
		}


		#endregion
		
	}
}
