
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class RECHT : DataObject
	{
		public RECHT() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{
            	"Id"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesRECHT
		{  
            public const string Id = "Id";
            public const string CountryId = "CountryId";
            public const string Omschrijving = "Omschrijving";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Id
	    {
			get
	        {
				return base.Getint(ColumnNamesRECHT.Id);
			}
			set
	        {
				base.Setint(ColumnNamesRECHT.Id, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int CountryId
	    {
			get
	        {
				return base.Getint(ColumnNamesRECHT.CountryId);
			}
			set
	        {
				base.Setint(ColumnNamesRECHT.CountryId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Omschrijving
	    {
			get
	        {
				return base.Getstring(ColumnNamesRECHT.Omschrijving);
			}
			set
	        {
				base.Setstring(ColumnNamesRECHT.Omschrijving, value);
			}
		}


		#endregion
		
	}
}
