
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class REPORT_INFORMATION : DataObject
	{
		public REPORT_INFORMATION() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Soaplog_ID",
            	"RI_ReportDate",
            	"MovID",
            	"EventID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesREPORT_INFORMATION
		{  
            public const string Soaplog_ID = "Soaplog_ID";
            public const string MovID = "MovID";
            public const string EventID = "EventID";
            public const string RI_ReportDate = "RI_ReportDate";
            public const string RI_From = "RI_From";
            public const string RI_To = "RI_To";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Soaplog_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_INFORMATION.Soaplog_ID);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_INFORMATION.Soaplog_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int MovID
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_INFORMATION.MovID);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_INFORMATION.MovID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int EventID
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_INFORMATION.EventID);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_INFORMATION.EventID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public DateTime RI_ReportDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesREPORT_INFORMATION.RI_ReportDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesREPORT_INFORMATION.RI_ReportDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int RI_From
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_INFORMATION.RI_From);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_INFORMATION.RI_From, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int RI_To
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_INFORMATION.RI_To);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_INFORMATION.RI_To, value);
			}
		}


		#endregion
		
	}
}
