
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class REPORT_LOGGING : DataObject
	{
		public REPORT_LOGGING() : base(Database.agrologs)
		{
			UpdateParams = new String[] 
			{
            	"Rl_Id"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesREPORT_LOGGING
		{  
            public const string Rl_Id = "rl_Id";
            public const string Rl_FarmId = "rl_FarmId";
            public const string Rl_UbnId = "rl_UbnId";
            public const string Rl_ThrId = "rl_ThrId";
            public const string Rl_ReportId = "rl_ReportId";
            public const string Rl_DateTime = "rl_DateTime";
            public const string Rl_State = "rl_State";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Rl_Id
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_Id);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_Id, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Rl_FarmId
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_FarmId);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_FarmId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Rl_UbnId
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_UbnId);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Rl_ThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_ThrId);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_ThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Rl_ReportId
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_ReportId);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_ReportId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Rl_DateTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesREPORT_LOGGING.Rl_DateTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesREPORT_LOGGING.Rl_DateTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Rl_State
	    {
			get
	        {
				return base.Getint(ColumnNamesREPORT_LOGGING.Rl_State);
			}
			set
	        {
				base.Setint(ColumnNamesREPORT_LOGGING.Rl_State, value);
			}
		}


		#endregion
		
	}
}
