
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class RUMALOG : DataObject
	{
		public RUMALOG() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesRUMALOG
		{  
            public const string UbnId = "UbnId";
            public const string LogDate = "LogDate";
            public const string LogTime = "LogTime";
            public const string Internalnr = "Internalnr";
            public const string LogText = "LogText";
            public const string LogPrintStatus = "LogPrintStatus";
            public const string LogKind = "LogKind";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string UbnId
	    {
			get
	        {
				return base.Getstring(ColumnNamesRUMALOG.UbnId);
			}
			set
	        {
				base.Setstring(ColumnNamesRUMALOG.UbnId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime LogDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesRUMALOG.LogDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesRUMALOG.LogDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime LogTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesRUMALOG.LogTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesRUMALOG.LogTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesRUMALOG.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesRUMALOG.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string LogText
	    {
			get
	        {
				return base.Getstring(ColumnNamesRUMALOG.LogText);
			}
			set
	        {
				base.Setstring(ColumnNamesRUMALOG.LogText, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LogPrintStatus
	    {
			get
	        {
				return base.Getint(ColumnNamesRUMALOG.LogPrintStatus);
			}
			set
	        {
				base.Setint(ColumnNamesRUMALOG.LogPrintStatus, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int LogKind
	    {
			get
	        {
				return base.Getint(ColumnNamesRUMALOG.LogKind);
			}
			set
	        {
				base.Setint(ColumnNamesRUMALOG.LogKind, value);
			}
		}


		#endregion
		
	}
}
