
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class SOAP_LOG : DataObject
	{
		public SOAP_LOG() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"SL_ID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesSOAP_LOG
		{  
            public const string SL_ID = "SL_ID";
            public const string SL_DateTime = "SL_DateTime";
            public const string SL_Lifenr = "SL_Lifenr";
            public const string SL_Farmnumber = "SL_Farmnumber";
            public const string SL_Meldnr = "SL_Meldnr";
            public const string SMS_ID = "SMS_ID";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int SL_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesSOAP_LOG.SL_ID);
			}
			set
	        {
				base.Setint(ColumnNamesSOAP_LOG.SL_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime SL_DateTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesSOAP_LOG.SL_DateTime);
			}
			set
	        {
				base.SetDateTime(ColumnNamesSOAP_LOG.SL_DateTime, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string SL_Lifenr
	    {
			get
	        {
				return base.Getstring(ColumnNamesSOAP_LOG.SL_Lifenr);
			}
			set
	        {
				base.Setstring(ColumnNamesSOAP_LOG.SL_Lifenr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string SL_Farmnumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesSOAP_LOG.SL_Farmnumber);
			}
			set
	        {
				base.Setstring(ColumnNamesSOAP_LOG.SL_Farmnumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string SL_Meldnr
	    {
			get
	        {
				return base.Getstring(ColumnNamesSOAP_LOG.SL_Meldnr);
			}
			set
	        {
				base.Setstring(ColumnNamesSOAP_LOG.SL_Meldnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SMS_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesSOAP_LOG.SMS_ID);
			}
			set
	        {
				base.Setint(ColumnNamesSOAP_LOG.SMS_ID, value);
			}
		}


		#endregion
		
	}
}
