
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class SUPPLY1 : DataObject
	{
		public SUPPLY1() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"SupplyId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesSUPPLY1
		{  
            public const string SupplyId = "SupplyId";
            public const string Factid = "Factid";
            public const string BoekstukNummer = "BoekstukNummer";
            public const string SupOrder = "SupOrder";
            public const string Artikelid = "Artikelid";
            public const string SupProcessed = "SupProcessed";
            public const string SupLeveringsDatum = "SupLeveringsDatum";
            public const string SupGrootboekId = "SupGrootboekId";
            public const string SupVolumeMeasurement = "SupVolumeMeasurement";
            public const string SupVolume = "SupVolume";
            public const string SupQuantityMeasurement = "SupQuantityMeasurement";
            public const string SupQuantity = "SupQuantity";
            public const string SupVoerGroup = "SupVoerGroup";
            public const string SupVem = "SupVem";
            public const string SupVevi = "SupVevi";
            public const string SupDVE = "SupDVE";
            public const string SupOEB = "SupOEB";
            public const string SupDryMatter = "SupDryMatter";
            public const string SupDryMatterMeasurement = "SupDryMatterMeasurement";
            public const string SupNormRE = "SupNormRE";
            public const string SupNormP = "SupNormP";
            public const string SupNormK = "SupNormK";
            public const string SupPayPriceTyp = "SupPayPriceTyp";
            public const string SupPayPrice = "SupPayPrice";
            public const string SupTotalPriceEx = "SupTotalPriceEx";
            public const string SupVatPrice = "SupVatPrice";
            public const string SupShowIncludingVat = "SupShowIncludingVat";
            public const string SupBTWId = "SupBTWId";
            public const string SupDiscount = "SupDiscount";
            public const string Orderid = "Orderid";
            public const string Ordervolgnummer = "Ordervolgnummer";
            public const string StorageId = "StorageId";
            public const string GroupId = "GroupId";
            public const string SupMemo = "SupMemo";
            public const string FarmId_Ontvanger = "FarmId_Ontvanger";
            public const string ExtDb_id = "extDb_id";
            public const string ExtDb_type = "extDb_type";
            public const string SupWerkId = "SupWerkId";
            public const string SupDatum = "SupDatum";
            public const string Sup_Ruma_ID = "Sup_Ruma_ID";
            public const string Sup_Batchnr = "Sup_Batchnr"; 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int SupplyId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupplyId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupplyId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Factid
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.Factid);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.Factid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int BoekstukNummer
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.BoekstukNummer);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.BoekstukNummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupOrder
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupOrder);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupOrder, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Artikelid
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.Artikelid);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.Artikelid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupProcessed
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupProcessed);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupProcessed, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime SupLeveringsDatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesSUPPLY1.SupLeveringsDatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesSUPPLY1.SupLeveringsDatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupGrootboekId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupGrootboekId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupGrootboekId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte SupVolumeMeasurement
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesSUPPLY1.SupVolumeMeasurement);
			}
			set
	        {
				base.Setsbyte(ColumnNamesSUPPLY1.SupVolumeMeasurement, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupVolume
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupVolume);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupVolume, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte SupQuantityMeasurement
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesSUPPLY1.SupQuantityMeasurement);
			}
			set
	        {
				base.Setsbyte(ColumnNamesSUPPLY1.SupQuantityMeasurement, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupQuantity
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupQuantity);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupQuantity, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupVoerGroup
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupVoerGroup);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupVoerGroup, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupVem
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupVem);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupVem, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupVevi
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupVevi);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupVevi, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupDVE
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupDVE);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupDVE, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupOEB
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupOEB);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupOEB, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupDryMatter
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupDryMatter);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupDryMatter, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte SupDryMatterMeasurement
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesSUPPLY1.SupDryMatterMeasurement);
			}
			set
	        {
				base.Setsbyte(ColumnNamesSUPPLY1.SupDryMatterMeasurement, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupNormRE
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupNormRE);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupNormRE, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupNormP
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupNormP);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupNormP, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupNormK
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupNormK);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupNormK, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte SupPayPriceTyp
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesSUPPLY1.SupPayPriceTyp);
			}
			set
	        {
				base.Setsbyte(ColumnNamesSUPPLY1.SupPayPriceTyp, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupPayPrice
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupPayPrice);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupPayPrice, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupTotalPriceEx
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupTotalPriceEx);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupTotalPriceEx, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupVatPrice
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupVatPrice);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupVatPrice, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte SupShowIncludingVat
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesSUPPLY1.SupShowIncludingVat);
			}
			set
	        {
				base.Setsbyte(ColumnNamesSUPPLY1.SupShowIncludingVat, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupBTWId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupBTWId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupBTWId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupDiscount
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1.SupDiscount);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1.SupDiscount, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Orderid
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.Orderid);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.Orderid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Ordervolgnummer
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.Ordervolgnummer);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.Ordervolgnummer, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int StorageId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.StorageId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.StorageId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int GroupId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.GroupId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.GroupId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string SupMemo
	    {
			get
	        {
				return base.Getstring(ColumnNamesSUPPLY1.SupMemo);
			}
			set
	        {
				base.Setstring(ColumnNamesSUPPLY1.SupMemo, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmId_Ontvanger
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.FarmId_Ontvanger);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.FarmId_Ontvanger, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ExtDb_id
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.ExtDb_id);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.ExtDb_id, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ExtDb_type
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.ExtDb_type);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.ExtDb_type, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int SupWerkId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.SupWerkId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.SupWerkId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime SupDatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesSUPPLY1.SupDatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesSUPPLY1.SupDatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Sup_Ruma_ID
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1.Sup_Ruma_ID);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1.Sup_Ruma_ID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Sup_Batchnr
	    {
			get
	        {
				return base.Getstring(ColumnNamesSUPPLY1.Sup_Batchnr);
			}
			set
	        {
				base.Setstring(ColumnNamesSUPPLY1.Sup_Batchnr, value);
			}
		}

		#endregion
		
	}
}
