
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class SUPPLY1_VOER : DataObject
	{
		public SUPPLY1_VOER() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"SupplyID"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesSUPPLY1_VOER
		{  
            public const string SupplyID = "SupplyID";
            public const string SupVoe_DateFrom = "SupVoe_DateFrom";
            public const string SupVoe_DateTo = "SupVoe_DateTo"; 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int SupplyID
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1_VOER.SupplyID);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1_VOER.SupplyID, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime SupVoe_DateFrom
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesSUPPLY1_VOER.SupVoe_DateFrom);
			}
			set
	        {
				base.SetDateTime(ColumnNamesSUPPLY1_VOER.SupVoe_DateFrom, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime SupVoe_DateTo
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesSUPPLY1_VOER.SupVoe_DateTo);
			}
			set
	        {
				base.SetDateTime(ColumnNamesSUPPLY1_VOER.SupVoe_DateTo, value);
			}
		}

		#endregion
		
	}
}
