
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class SUPPLY1_GROUP : DataObject
	{
		public SUPPLY1_GROUP() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"SupplyId",
            	"GroupId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesSUPPLY1_GROUP
		{  
            public const string SupplyId = "supplyId";
            public const string GroupId = "groupId";
            public const string SupVolume = "supVolume";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int SupplyId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1_GROUP.SupplyId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1_GROUP.SupplyId, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int GroupId
	    {
			get
	        {
				return base.Getint(ColumnNamesSUPPLY1_GROUP.GroupId);
			}
			set
	        {
				base.Setint(ColumnNamesSUPPLY1_GROUP.GroupId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double SupVolume
	    {
			get
	        {
				return base.Getdouble(ColumnNamesSUPPLY1_GROUP.SupVolume);
			}
			set
	        {
				base.Setdouble(ColumnNamesSUPPLY1_GROUP.SupVolume, value);
			}
		}


		#endregion
		
	}
}
