
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class THIRD_LOGIN_LIST : DataObject
	{
		public THIRD_LOGIN_LIST() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"ThrSoort"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesTHIRD_LOGIN_LIST
		{  
            public const string ThrSoort = "ThrSoort";
            public const string HostName = "HostName";
            public const string PassiveMode = "PassiveMode";
            public const string Description = "Description";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ThrSoort
	    {
			get
	        {
				return base.Getint(ColumnNamesTHIRD_LOGIN_LIST.ThrSoort);
			}
			set
	        {
				base.Setint(ColumnNamesTHIRD_LOGIN_LIST.ThrSoort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string HostName
	    {
			get
	        {
				return base.Getstring(ColumnNamesTHIRD_LOGIN_LIST.HostName);
			}
			set
	        {
				base.Setstring(ColumnNamesTHIRD_LOGIN_LIST.HostName, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public sbyte PassiveMode
	    {
			get
	        {
				return base.Getsbyte(ColumnNamesTHIRD_LOGIN_LIST.PassiveMode);
			}
			set
	        {
				base.Setsbyte(ColumnNamesTHIRD_LOGIN_LIST.PassiveMode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Description
	    {
			get
	        {
				return base.Getstring(ColumnNamesTHIRD_LOGIN_LIST.Description);
			}
			set
	        {
				base.Setstring(ColumnNamesTHIRD_LOGIN_LIST.Description, value);
			}
		}


		#endregion
		
	}
}
