
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class TOKEN : DataObject
	{
		public TOKEN() : base(Database.agrolink)
		{
			UpdateParams = new String[] 
			{
            	"TokToken"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesTOKEN
		{  
            public const string TokToken = "TokToken";
            public const string ThrId = "ThrId";
            public const string Ins = "ins";
            public const string Ts = "ts";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public string TokToken
	    {
			get
	        {
				return base.Getstring(ColumnNamesTOKEN.TokToken);
			}
			set
	        {
				base.Setstring(ColumnNamesTOKEN.TokToken, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesTOKEN.ThrId);
			}
			set
	        {
				base.Setint(ColumnNamesTOKEN.ThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Ins
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesTOKEN.Ins);
			}
			set
	        {
				base.SetDateTime(ColumnNamesTOKEN.Ins, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Ts
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesTOKEN.Ts);
			}
			set
	        {
				base.SetDateTime(ColumnNamesTOKEN.Ts, value);
			}
		}


		#endregion
		
	}
}
