
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class TRANSMIT : DataObject
	{
		public TRANSMIT() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesTRANSMIT
		{  
            public const string FarmNumber = "FarmNumber";
            public const string AniId = "AniId";
            public const string Koppelnr = "Koppelnr";
            public const string TransmitterNumber = "TransmitterNumber";
            public const string Worknumber = "Worknumber";
            public const string ProcesComputerId = "ProcesComputerId";
            public const string farmid = "farmid";
            public const string UbnID = "UbnID";           
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string FarmNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesTRANSMIT.FarmNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesTRANSMIT.FarmNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int AniId
	    {
			get
	        {
				return base.Getint(ColumnNamesTRANSMIT.AniId);
			}
			set
	        {
				base.Setint(ColumnNamesTRANSMIT.AniId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Koppelnr
	    {
			get
	        {
				return base.Getint(ColumnNamesTRANSMIT.Koppelnr);
			}
			set
	        {
				base.Setint(ColumnNamesTRANSMIT.Koppelnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string TransmitterNumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesTRANSMIT.TransmitterNumber);
			}
			set
	        {
				base.Setstring(ColumnNamesTRANSMIT.TransmitterNumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Worknumber
	    {
			get
	        {
				return base.Getstring(ColumnNamesTRANSMIT.Worknumber);
			}
			set
	        {
				base.Setstring(ColumnNamesTRANSMIT.Worknumber, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ProcesComputerId
	    {
			get
	        {
				return base.Getint(ColumnNamesTRANSMIT.ProcesComputerId);
			}
			set
	        {
				base.Setint(ColumnNamesTRANSMIT.ProcesComputerId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int farmid
	    {
			get
	        {
				return base.Getint(ColumnNamesTRANSMIT.farmid);
			}
			set
	        {
				base.Setint(ColumnNamesTRANSMIT.farmid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int UbnID
	    {
			get
	        {
				return base.Getint(ColumnNamesTRANSMIT.UbnID);
			}
			set
	        {
				base.Setint(ColumnNamesTRANSMIT.UbnID, value);
			}
		}
		#endregion
		
	}
}
