
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class USECRVNM : DataObject
	{
		public USECRVNM() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"Internalnr"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesUSECRVNM
		{  
            public const string FarmID = "FarmID";
            public const string Internalnr = "Internalnr";
            public const string Soort = "Soort";
            public const string Omschrijving = "Omschrijving";
            public const string Groupnr = "Groupnr";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVNM.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVNM.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVNM.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVNM.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Soort
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVNM.Soort);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVNM.Soort, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Omschrijving
	    {
			get
	        {
				return base.Getstring(ColumnNamesUSECRVNM.Omschrijving);
			}
			set
	        {
				base.Setstring(ColumnNamesUSECRVNM.Omschrijving, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Groupnr
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVNM.Groupnr);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVNM.Groupnr, value);
			}
		}

		#endregion
		
	}
}
