
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class USECRVDT : DataObject
	{
		public USECRVDT() : base(Database.animal)
		{
			UpdateParams = new String[] 
			{
            	"FarmID",
            	"Internalnr",
            	"StartDate"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesUSECRVDT
		{  
            public const string FarmID = "FarmID";
            public const string Internalnr = "Internalnr";
            public const string StartDate = "StartDate";
            public const string InternalCurvenr = "InternalCurvenr";
            public const string EndDate = "EndDate";          
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVDT.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVDT.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int Internalnr
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVDT.Internalnr);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVDT.Internalnr, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public DateTime StartDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesUSECRVDT.StartDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesUSECRVDT.StartDate, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int InternalCurvenr
	    {
			get
	        {
				return base.Getint(ColumnNamesUSECRVDT.InternalCurvenr);
			}
			set
	        {
				base.Setint(ColumnNamesUSECRVDT.InternalCurvenr, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime EndDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesUSECRVDT.EndDate);
			}
			set
	        {
				base.SetDateTime(ColumnNamesUSECRVDT.EndDate, value);
			}
		}

		#endregion
		
	}
}
