
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class VERIFIED_MOVEMENT_SANITEL : DataObject
	{
		public VERIFIED_MOVEMENT_SANITEL()
		{
		}

	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AnimalLifenumber = "AnimalLifenumber";
            public const string MovementDate = "MovementDate";
            public const string MovementOrder = "MovementOrder";
            public const string MovementNotificationType = "MovementNotificationType";
            public const string MovementAnimalCondition = "MovementAnimalCondition";
            public const string MovementSourceSanitaryUnit = "MovementSourceSanitaryUnit";
            public const string MovementDestinationSanitaryUnit = "MovementDestinationSanitaryUnit";
            public const string MovementSourceFacility = "MovementSourceFacility";
            public const string MovementDestinationFacility = "MovementDestinationFacility";
            public const string Changed_By = "Changed_By";
            public const string SourceID = "SourceID";
		}
		#endregion

		#region Properties
	
		public string AnimalLifenumber
	    {
			get
	        {
				return base.Getstring(ColumnNames.AnimalLifenumber);
			}
			set
	        {
				base.Setstring(ColumnNames.AnimalLifenumber, value);
			}
		}

		public DateTime MovementDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.MovementDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.MovementDate, value);
			}
		}

		public int MovementOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.MovementOrder);
			}
			set
	        {
				base.Setint(ColumnNames.MovementOrder, value);
			}
		}

		public string MovementNotificationType
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementNotificationType);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementNotificationType, value);
			}
		}

		public string MovementAnimalCondition
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementAnimalCondition);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementAnimalCondition, value);
			}
		}

		public string MovementSourceSanitaryUnit
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementSourceSanitaryUnit);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementSourceSanitaryUnit, value);
			}
		}

		public string MovementDestinationSanitaryUnit
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementDestinationSanitaryUnit);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementDestinationSanitaryUnit, value);
			}
		}

		public string MovementSourceFacility
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementSourceFacility);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementSourceFacility, value);
			}
		}

		public string MovementDestinationFacility
	    {
			get
	        {
				return base.Getstring(ColumnNames.MovementDestinationFacility);
			}
			set
	        {
				base.Setstring(ColumnNames.MovementDestinationFacility, value);
			}
		}

		public int Changed_By
	    {
			get
	        {
				return base.Getint(ColumnNames.Changed_By);
			}
			set
	        {
				base.Setint(ColumnNames.Changed_By, value);
			}
		}

		public int SourceID
	    {
			get
	        {
				return base.Getint(ColumnNames.SourceID);
			}
			set
	        {
				base.Setint(ColumnNames.SourceID, value);
			}
		}


		#endregion
		
	}
}
