
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class VISITS : DataObject
	{
		public VISITS() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"BezoekId"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesVISITS
		{  
            public const string ThrId = "ThrId";
            public const string FarmID = "FarmID";
            public const string BezoekId = "BezoekId";
            public const string Bezoekdatum = "Bezoekdatum";
            public const string Begintijd = "Begintijd";
            public const string Eindtijd = "Eindtijd";
            public const string Reden = "Reden";
            public const string Soort = "Soort";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ThrId
	    {
			get
	        {
				return base.Getint(ColumnNamesVISITS.ThrId);
			}
			set
	        {
				base.Setint(ColumnNamesVISITS.ThrId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int FarmID
	    {
			get
	        {
				return base.Getint(ColumnNamesVISITS.FarmID);
			}
			set
	        {
				base.Setint(ColumnNamesVISITS.FarmID, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, true, false)] 
		public int BezoekId
	    {
			get
	        {
				return base.Getint(ColumnNamesVISITS.BezoekId);
			}
			set
	        {
				base.Setint(ColumnNamesVISITS.BezoekId, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Bezoekdatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesVISITS.Bezoekdatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesVISITS.Bezoekdatum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Begintijd
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesVISITS.Begintijd);
			}
			set
	        {
				base.SetDateTime(ColumnNamesVISITS.Begintijd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Eindtijd
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesVISITS.Eindtijd);
			}
			set
	        {
				base.SetDateTime(ColumnNamesVISITS.Eindtijd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Reden
	    {
			get
	        {
				return base.Getstring(ColumnNamesVISITS.Reden);
			}
			set
	        {
				base.Setstring(ColumnNamesVISITS.Reden, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Soort
	    {
			get
	        {
				return base.Getint(ColumnNamesVISITS.Soort);
			}
			set
	        {
				base.Setint(ColumnNamesVISITS.Soort, value);
			}
		}


		#endregion
		
	}
}
