
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class WEERINFO_KNMI : DataObject
	{
		public WEERINFO_KNMI() : base(Database.agrodata)
		{
			UpdateParams = new String[] 
			{

			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesWEERINFO_KNMI
		{  
            public const string Stationcode = "stationcode";
            public const string Datum = "datum";
            public const string Tijd = "tijd";
            public const string Windrichting = "windrichting";
            public const string WindsnelheidMS = "windsnelheidMS";
            public const string WindstotenMS = "windstotenMS";
            public const string TemperatuurGC = "temperatuurGC";
            public const string Temperatuur10cm = "temperatuur10cm";
            public const string Dauwpuntstemperatuur = "dauwpuntstemperatuur";
            public const string Duur_zonneschijn = "duur_zonneschijn";
            public const string Duur_neerslag = "duur_neerslag";
            public const string Uursom_neerslag = "uursom_neerslag";
            public const string Luchtdruk = "luchtdruk";
            public const string Horizontaal_zicht = "horizontaal_zicht";
            public const string Luchtvochtigheid = "luchtvochtigheid";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Stationcode
	    {
			get
	        {
				return base.Getstring(ColumnNamesWEERINFO_KNMI.Stationcode);
			}
			set
	        {
				base.Setstring(ColumnNamesWEERINFO_KNMI.Stationcode, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime Datum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesWEERINFO_KNMI.Datum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesWEERINFO_KNMI.Datum, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Tijd
	    {
			get
	        {
				return base.Getint(ColumnNamesWEERINFO_KNMI.Tijd);
			}
			set
	        {
				base.Setint(ColumnNamesWEERINFO_KNMI.Tijd, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string Windrichting
	    {
			get
	        {
				return base.Getstring(ColumnNamesWEERINFO_KNMI.Windrichting);
			}
			set
	        {
				base.Setstring(ColumnNamesWEERINFO_KNMI.Windrichting, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double WindsnelheidMS
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.WindsnelheidMS);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.WindsnelheidMS, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double WindstotenMS
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.WindstotenMS);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.WindstotenMS, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double TemperatuurGC
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.TemperatuurGC);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.TemperatuurGC, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Temperatuur10cm
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Temperatuur10cm);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Temperatuur10cm, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Dauwpuntstemperatuur
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Dauwpuntstemperatuur);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Dauwpuntstemperatuur, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Duur_zonneschijn
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Duur_zonneschijn);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Duur_zonneschijn, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Duur_neerslag
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Duur_neerslag);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Duur_neerslag, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Uursom_neerslag
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Uursom_neerslag);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Uursom_neerslag, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double Luchtdruk
	    {
			get
	        {
				return base.Getdouble(ColumnNamesWEERINFO_KNMI.Luchtdruk);
			}
			set
	        {
				base.Setdouble(ColumnNamesWEERINFO_KNMI.Luchtdruk, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Horizontaal_zicht
	    {
			get
	        {
				return base.Getint(ColumnNamesWEERINFO_KNMI.Horizontaal_zicht);
			}
			set
	        {
				base.Setint(ColumnNamesWEERINFO_KNMI.Horizontaal_zicht, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int Luchtvochtigheid
	    {
			get
	        {
				return base.Getint(ColumnNamesWEERINFO_KNMI.Luchtvochtigheid);
			}
			set
	        {
				base.Setint(ColumnNamesWEERINFO_KNMI.Luchtvochtigheid, value);
			}
		}


		#endregion
		
	}
}
