
/*
'===============================================================================
'  Generated From - CSharp_VSM_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class  is in the Architecture directory in "VSM".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

using System.Collections;
using System.Collections.Specialized;


namespace VSM.RUMA.CORE.DB.DataTypes
{
    [Serializable()]
	public class ZAAIPTN : DataObject
	{
		public ZAAIPTN() : base(Database.agrofactuur)
		{
			UpdateParams = new String[] 
			{
            	"ZpPerceelid",
            	"ZpActid"
			};
		
		}

	
		#region ColumnNames
		public class ColumnNamesZAAIPTN
		{  
            public const string ZpPerceelid = "ZpPerceelid";
            public const string ZpActid = "ZpActid";
            public const string ZpGewas = "ZpGewas";
            public const string ZpRas = "ZpRas";
            public const string ZpHoeveelheid = "ZpHoeveelheid";
            public const string ZpEenheid = "ZpEenheid";
            public const string ZpOpkomstdatum = "ZpOpkomstdatum";
 

		}
		#endregion




		#region Properties
	
		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ZpPerceelid
	    {
			get
	        {
				return base.Getint(ColumnNamesZAAIPTN.ZpPerceelid);
			}
			set
	        {
				base.Setint(ColumnNamesZAAIPTN.ZpPerceelid, value);
			}
		}

		[System.ComponentModel.DataObjectField(true, false, false)] 
		public int ZpActid
	    {
			get
	        {
				return base.Getint(ColumnNamesZAAIPTN.ZpActid);
			}
			set
	        {
				base.Setint(ColumnNamesZAAIPTN.ZpActid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ZpGewas
	    {
			get
	        {
				return base.Getint(ColumnNamesZAAIPTN.ZpGewas);
			}
			set
	        {
				base.Setint(ColumnNamesZAAIPTN.ZpGewas, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public string ZpRas
	    {
			get
	        {
				return base.Getstring(ColumnNamesZAAIPTN.ZpRas);
			}
			set
	        {
				base.Setstring(ColumnNamesZAAIPTN.ZpRas, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public double ZpHoeveelheid
	    {
			get
	        {
				return base.Getdouble(ColumnNamesZAAIPTN.ZpHoeveelheid);
			}
			set
	        {
				base.Setdouble(ColumnNamesZAAIPTN.ZpHoeveelheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public int ZpEenheid
	    {
			get
	        {
				return base.Getint(ColumnNamesZAAIPTN.ZpEenheid);
			}
			set
	        {
				base.Setint(ColumnNamesZAAIPTN.ZpEenheid, value);
			}
		}

		[System.ComponentModel.DataObjectField(false, false, false)] 
		public DateTime ZpOpkomstdatum
	    {
			get
	        {
				return base.GetDateTime(ColumnNamesZAAIPTN.ZpOpkomstdatum);
			}
			set
	        {
				base.SetDateTime(ColumnNamesZAAIPTN.ZpOpkomstdatum, value);
			}
		}


		#endregion
		
	}
}
