//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSM.RUMA.CORE.SOAPLNV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dbrbms.agro.nl/bms_v2_0/services/ReferentieWS")]
        public string VSM_RUMA_CORE_SOAPLNV_LNVReferentie_ReferentieServiceService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_LNVReferentie_ReferentieServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dbrbms.agro.nl/bms_v2_0/services/DierenWS")]
        public string VSM_RUMA_CORE_SOAPLNV_DierenWS_DierenServiceService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_DierenWS_DierenServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dbrbms.agro.nl/bms_v2_0/services/MachtigingenWS")]
        public string VSM_RUMA_CORE_SOAPLNV_MachtigingenWS_MachtigingenServiceService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_MachtigingenWS_MachtigingenServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dbrbms.agro.nl/bms_v2_0/services/MerkenWS")]
        public string VSM_RUMA_CORE_SOAPLNV_MerkenWS_MerkenServiceService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_MerkenWS_MerkenServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://HOST/bms_v2_0/services/MeldingenWS")]
        public string VSM_RUMA_CORE_SOAPLNV_nl_agro_dbrbms_MeldingenServiceService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_nl_agro_dbrbms_MeldingenServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dbrbms.agro.nl/osbbms_v2_0/services/MeldingenWS")]
        public string VSM_RUMA_CORE_SOAPLNV_MeldingewnWS_MeldingenWSSoapBindingImplService {
            get {
                return ((string)(this["VSM_RUMA_CORE_SOAPLNV_MeldingewnWS_MeldingenWSSoapBindingImplService"]));
            }
        }
    }
}
